### ISSUE TITLE
CMP Hash Configuration support for vlan

### ISSUE THREAD

**Issue by rdalbenzio** [F5Networks/f5-declarative-onboarding#1]
Apparently DAG configuration is not part of the initial support. Would be good to be added, if we want to use DO for Modules like AFM/CGNAT or PEM.

**Comment by jgruber** [comment]
Raffaele, D0 scope is to handle the orchestration of TMOS classic features. DAG is a specific orchestration for a specific architecture.

We are looking for requests which can be used to compose your DAG request, but please be specific on what TMOS classic features you want to be able to declare per device. That's D0's scope.

We are working through requirements for interface, VLAN, tunneling, routes, NAT, SNAT Pool/SNAT Translation Address provisioning.

**Comment by rdalbenzio** [comment]
Hello John,

Sorry, my request was not clear.

What I referred to is an interface specific function called “CMP Hash” (Default/Src/Dst IP as options), which is configured at VLAN level.

In my view we need to be able to do it during the onboarding phase, hence the request on the DO part.

Sorry for not being clear.

I can change the request if needed.

Raf.

**Comment by jgruber** [comment]
New title looks great. Thanks.

**Comment by focrensh** [comment]
Tracked internally with ticket 102.

**Comment by dstokesf5** [comment]
This was addressed several versions ago. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.
