### ISSUE TITLE
Undefined SSH keys treated as empty array

### ISSUE THREAD

**Issue by vbojko** [F5Networks/f5-declarative-onboarding#101]
### Is your feature request related to a problem? Please describe.
DO deletes any user ssh key on box if the user is declared in the declaration and the ssh key is not provided in the declaration.
this is problematic in public cloud environments, like AWS, where the access to the BIG-IP instances is granted through ssh keys for admin user and the admin user does not have a password set by default.

In the first 4 example declaration of DO the admin user is declared with an admin password, but no SSH key.
Now if a user sends these declaration the ssh key on box is deleted and the user is not able to login to the instance with the ssh key again. this can cause problems for a lot of reasons.

In the documentation of example 5 there is a side note and in the description for keys in the schema this behaviour is mentioned. This is already too late and the behaviour should be stated clearly before the first DO example.

### Describe the solution you'd like

My feature request is to put a clear visible note or warning before the first declaration that states that the following declarations will delete the admin ssh key and in case the admin ssh key should be preserved to check how to do it in example 5.

### Describe alternatives you've considered

There is some description in the documentation, but it is too late in the documentation and not clear visible.

**Comment by dstokesf5** [comment]
I have added this as AUTOTOOL-1157 in our internal product backlog. I have changed this to a bug since we should really be improving the behavior here to avoid nasty surprises. If a user does not declare SSH keys, then we should not be assuming that means an empty list of keys, and DO should probably just leave the keys alone.

**Comment by dstokesf5** [comment]
This issue has been resolved with the 1.23.0 release of Declarative Onboarding.
