### ISSUE TITLE
Documentation enhancement request: make DO RPM easier to find

### ISSUE THREAD

**Issue by vbojko** [F5Networks/f5-declarative-onboarding#102]
### Is your feature request related to a problem? Please describe.

Please make the link to the github releases easier to find.
Please add a download button on top of the documentation instead of hiding it behind the github release hyperlink in the middle of the text.

Second: Add a link to the API, becasue It is required for the automatic download of the filed from the releases. this link.

### Describe the solution you'd like

Please make an download button that is labeled: Download PRM here on top of the prerequisites page or entry page.
The link to the releases is a hyperlink somewhere down below in the notes.IT should be easier to find and should not require me to read through a ton of text to eventually find or not find a hyperlink hidden is a pile of text.

**Comment by dstokesf5** [comment]
Thank you for your feedback, I have added AUTOTOOL-1208 to our internal product backlog to improve the visibility of the releases URL in the Declarative Onboarding documentation.

**Comment by JosephPJordan** [comment]
Hello @vbojko, we've added a link to the DO home page in the 1.11 release (https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/index.html).  It was already in an important note in the Downloading section: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/installation.html, and is at the top of the Notes in https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/prereqs.html#notes-and-tips.  For the next release, we will be adding a Quick Start page, and it will also be there.
