### ISSUE TITLE
Ability to set software update auto-check

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-declarative-onboarding#107]
### Is your feature request related to a problem? Please describe.
I'm working off a standard build document for an environment, we turn off the auto-check by default as internet access from F5 isn't allowed. We are trying to match features from the standard build with DO features.

### Describe the solution you'd like
The ability to set the software update auto-check to false using Declarative Onboarding.

https://support.f5.com/csp/article/K15000

### Describe alternatives you've considered
Until this is implemented I will consider using Ansible modules or REST API.

### Additional context

Using tmsh:
   modify sys software update auto-check disabled

--

**Comment by dstokesf5** [comment]
Thank you for your input, I have added this feedback to our internal product backlog as AUTOTOOL-1236.

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 1.13.0 release.
