### ISSUE TITLE
provision all modules at once

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-declarative-onboarding#11]
when provisioning several modules in the deceleration, DO provision them one by one resulting in a big delay.

desired behavior - all modules should be provisioned at once to save time.

thanks 

sample declaration: 
    "declaration": {
        "async": true,
        "schemaVersion": "1.1.0",
        "class": "Device",
        "Common": {
            "myDns": {
                "nameServers": [
                    "8.8.8.8"
                ],
                "search": [
                    "f5.com",
                    "test.com"
                ],
                "class": "DNS"
            },
            "hostname": "udflab.demo",
            "myNtp": {
                "timezone": "UTC",
                "class": "NTP",
                "servers": [
                    "0.pool.ntp.org",
                    "1.pool.ntp.org"
                ]
            },
            "myProvisioning": {
                "afm": "nominal",
                "avr": "nominal",
                "ltm": "nominal",
                "fps": "nominal",
                "class": "Provision",
                "asm": "nominal"
            },
            "class": "Tenant",
            "myLicense": {
                "licensePool": "pool",
                "licenseType": "licensePool",
                "bigIqHost": "host",
                "bigIqUsername": "user",
                "skuKeyword1": "F5-BIG-MSPBTAWF1GIPIY",
                "unitOfMeasure": "yearly",
                "bigIpUsername": "admin",
                "reachable": false,
                "hypervisor": "aws",
                "class": "License"
            }
        }
    }

**Comment by seattlevine** [comment]
Tracking with internal issue 214

**Comment by focrensh** [comment]
AT-112 internal.

**Comment by seattlevine** [comment]
We have no way to provision multiple modules at once via BIG-IP API. This is an issue with BIG-IP.
