### ISSUE TITLE
Ability to set GUI security banner

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-declarative-onboarding#110]
### Is your feature request related to a problem? Please describe.
I'm working off a standard build document for an environment, this would satisfy our requirement for a GUI security banner.  We are trying to match features from the standard build with DO.

### Describe the solution you'd like
I would like the ability to set the GUI security banner using Declarative Onboarding.  Also the ability to enable (or disable) the banner, perhaps this can be implicit when setting the banner?

### Describe alternatives you've considered
Until this is implemented I will consider using Ansible modules or REST API.

### Additional context

Using tmsh:
   modify sys global-settings gui-security-banner-text    "**** This is my security banner ****"
   modify sys global-settings gui-security-banner enabled

--

**Comment by Mikej81** [comment]
This works today.  Example:  [https://github.com/Mikej81/f5-securecloud-DO/blob/master/dist/latest/3NIC_1Tier_HA/f5vm0.json](https://github.com/Mikej81/f5-securecloud-DO/blob/master/dist/latest/3NIC_1Tier_HA/f5vm0.json)

`
...
"Common": {
        "class": "Tenant",
        "hostname": "f5vm0.eastus.cloudapp.azure.com",
        "gui-security-banner": "enabled",
        "gui-security-banner-text": "You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. By using this IS (which includes any device attached to this IS), you consent to the following conditions: The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations. At any time, the USG may inspect and seize data stored on this IS. Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG authorized purpose. This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy. Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.",
        "dbvars": {
        	"class": "DbVariables",
        	"ui.advisory.enabled": true,
        	"ui.advisory.color": "green",
            "ui.advisory.text": "//UNCLASSIFIED//",
...`

**Comment by LeonardosGitHub** [comment]
@Mikej81  thanks for the info! 

@F5Networks - Please use this as a request to document this on clouddocs.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I looked around in Declarative Onboarding, and I could not find gui-security-banner being handled anywhere. I created AUTOTOOL-1306 in our internal product backlog to track this feature request. If it turns out to already be supported as suggested above, we will reuse the ticket to document the feature.

**Comment by erjac77** [comment]
For me it doesn't work. I got a "success" message, but the banner remains unchanged. I even tried to put the properties in camel case like all the others DO properties, same result...

**Comment by Mikej81** [comment]
@erjac77 I thought it had worked at some point, but I tested today and you are correct.

**Comment by grf5** [comment]
I also need this support. This is a security best practices configuration item.

**Comment by mdditt2000** [comment]
Resolved in AUTOTOOL-3413
Resolved in https://github.com/F5Networks/f5-declarative-onboarding/releases/tag/v1.33.0
Duplicate of https://github.com/F5Networks/f5-declarative-onboarding/issues/316
