### ISSUE TITLE
Ability to set mirror ip for a device

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-declarative-onboarding#112]
### Is your feature request related to a problem? Please describe.
I'm working off a standard build document for an environment, this is necessary to mirror traffic to the HA device.  We are trying to match features from the standard build with DO.

### Describe the solution you'd like

I would like the ability to set a mirror-ip for a device using Declarative Onboarding.

https://support.f5.com/csp/article/K13478

### Describe alternatives you've considered
Until this is implemented I will consider using Ansible modules or REST API.

### Additional context

Using tmsh:
   modify cm device bigip1 mirror-ip 10.1.1.1 mirror-secondary-ip 10.2.2.2

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this to our internal product backlog as AUTOTOOL-1374.

**Comment by dstokesf5** [comment]
This issue was resolved in the 1.16.0 release.
