### ISSUE TITLE
remote authentication with Active Directory (ldaps)

### ISSUE THREAD

**Issue by tizianorosato-gr** [F5Networks/f5-declarative-onboarding#119]
### Is your feature request related to a problem? Please describe.
We use remote authentication with Active Directory (ldaps) on our devices.
There is no way atm to confgurei t with DO

### Describe the solution you'd like
the ability to configure remote authentication with Active Directory (ldaps)

### Describe alternatives you've considered
none

### Additional context
none

**Comment by dstokesf5** [comment]
In order to make sure we expose the right properties, can you provide an example configuration?

**Comment by dstokesf5** [comment]
I have added this request to our internal product backlog as AUTOTOOL-1323.

**Comment by dstokesf5** [comment]
This was already added in previous versions of Declarative Onboarding: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/bigip-examples.html#configuring-big-ip-authentication-methods

If this does not satisfy your use case, please reopen this issue or create a new one.
