### ISSUE TITLE
ability to manage tunnel

### ISSUE THREAD

**Issue by tizianorosato-gr** [F5Networks/f5-declarative-onboarding#123]
### Is your feature request related to a problem? Please describe.
Ability to manage tunnel: create, delete, amend

### Describe the solution you'd like
Ability to manage tunnel: create, delete, amend

### Describe alternatives you've considered
none

### Additional context
this is an important config item when using the F5 as "Forward Proxy"

**Comment by dstokesf5** [comment]
Can you elaborate on what kind of tunneling you want to configure? It would be very helpful to have a tmsh create command that shows what kind of tunnel configuration you need.

We already have a request for GRE tunnels (#98). Do you need the same kind of tunneling, or a different kind of tunneling.

**Comment by tizianorosato-gr** [comment]
“tcp-forward” is the one I’m interested in.


[cid:image001.png@01D5F850.649AB3F0]

BR,
Tiziano

**Comment by dstokesf5** [comment]
This is being tracked in our internal product backlog as AUTOTOOL-1358.

**Comment by LeonardosGitHub** [comment]
+1 for feature

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 1.14.0 release.
