### ISSUE TITLE
Ability to configure routing protocols as part of Declarative Onboarding

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-declarative-onboarding#124]
I would like to set the BGP configurations using Declarative Onboarding. Looking for similar functionality that's available using the Ansible module [bigip_imish_config](https://docs.ansible.com/ansible/latest/modules/bigip_imish_config_module.html). 

### Describe alternatives you've considered

As mentioned above this could be accomplished with Ansible module, would like to leverage DO to accomplish this task. 

### Additional context

[Configuring the BIG-IP system for basic BGP connectivity](https://support.f5.com/csp/article/K54334475)

[Configuring BGP and BFD with iControl REST](https://techdocs.f5.com/en-us/bigip-14-0-0/big-ip-dynamic-routing-with-tmsh-and-icontrol-rest-14-0-0/configuring-dynamic-routing-with-icontrol-rest.html#GUID-C59C3150-150C-4C98-BC4C-2BE102A700D3)

Example complete configuration:

no service password-encryption
log file /var/log/zebos.log
no banner motd
bgp extended-asn-cap 
router bgp 65010
bgp router-id 10.1.1.1
bgp graceful-restart restart-time 120
redistribute kernel route-map route_map__1_name
timers bgp 10 35
neighbor Neighbor_IN peer-group
neighbor Neighbor_IN soft-reconfiguration inbound
neighbor Neighbor_IN route-map route_map__2_name out
neighbor Neighbor_IN remote-as 65020
neighbor Neighbor_OUT peer-group
neighbor Neighbor_OUT soft-reconfiguration inbound
neighbor Neighbor_OUT route-map  route_map__3_name out
neighbor Neighbor_OUT remote-as 65020
neighbor 10.1.1.2 peer-group Neighbor_OUT
neighbor 10.1.1.3 peer-group Neighbor_OUT
neighbor 10.1.1.4 peer-group Neighbor_IN
neighbor 10.1.1.5 peer-group Neighbor_IN
ip as-path access-list access_list__1_name permit ^65001 *
ip as-path access-list access_list__2_name permit ^$
ip as-path access-list access_list__2_name permit ^65005$
ip prefix-list prefix_list__1_name seq 10 permit 10.2.2.0/24 ge 32
route-map route_map__3_name permit 10
 match as-path access_list__2_name
route-map route_map__2_name permit 10
 match as-path access_list__1_name
route-map route_map__1_name permit 50
 match ip address prefix-list prefix_list__1_name

**Comment by dstokesf5** [comment]
It appears BGP can be configured via tmsh: https://techdocs.f5.com/en-us/bigip-14-0-0/big-ip-dynamic-routing-with-tmsh-and-icontrol-rest-14-0-0/configuring-dynamic-routing-with-tmsh.html#GUID-20A91569-6C61-4417-8BF0-BA7C2BCE5CA0

Is it possible to get an example of the desired configuration as tmsh configuration? It is significantly easier to add this feature to DO via tmsh than it is to add imish configuration capabilities.

**Comment by LeonardosGitHub** [comment]
@dstokesf5 here you go, these tmsh commands mirror the imish configuration above. 


modify sys db tmrouted.tmos.routing value enable   
        *db updated to enable the ability to use tmsh 
modify net routing profile bgp bgp extended-asn-cap enabled
create net routing as-path access_list__1_name entries add { 10 { action permit regex '^65001 *'}}
create net routing as-path access_list__2_name entries add { 10 { action permit regex '^$'} 20 { action permit regex '^65005$'} }
create net routing prefix-list prefix_list__1_name entries add { 10 { action permit prefix 10.2.2.0/24 prefix-len-range 32}  }
create net routing route-map route_map__3_name entries add { 10 { action permit match { as-path access_list__2_name }}}
create net routing route-map route_map__2_name entries add { 10 { action permit match { as-path access_list__1_name }}}
create net routing route-map route_map__1_name entries add { 50 { action permit match { ipv4 { address { prefix-list prefix_list__1_name }}}}}
create net routing bgp test local-as 65010 router-id 10.1.1.1 graceful-restart {restart-time 120} keep-alive 10 hold-time 35 address-family { ipv4 { redistribute add { kernel { route-map route_map__1_name }}}}
modify net routing bgp test peer-group add { Neighbor_IN {remote-as 65020 address-family {ipv4 {soft-reconfiguration-inbound enabled route-map { out route_map__2_name }}}}}
modify net routing bgp test peer-group add { Neighbor_OUT {remote-as 65020 address-family {ipv4 {soft-reconfiguration-inbound enabled route-map { out route_map__3_name }}}}}
modify net routing bgp test neighbor add {10.1.1.2 { peer-group Neighbor_OUT }}
modify net routing bgp test neighbor add {10.1.1.3 { peer-group Neighbor_OUT }}
modify net routing bgp test neighbor add {10.1.1.4 { peer-group Neighbor_IN }}
modify net routing bgp test neighbor add {10.1.1.5 { peer-group Neighbor_IN }}

**Comment by dstokesf5** [comment]
@LeonardosGitHub Thank for the tmsh configuration, that is extremely helpful and insightful. We have this tracked as an epic in our internal product backlog as AUTOTOOL-1522.

**Comment by jtylershaw** [comment]
The tmsh and iControl configuration for BIG-IP is fairly limited and not documented well and limited in scope to begin with (portions of BGP and .  A possibility would be to accept a congif file, or the contents of the config file, as part of the declaration and then just activate the routing protoclol(s) as needed.  Until the full gamut of routing protocols are available via API this might be a better option.

**Comment by jmcalalang** [comment]
@dstokesf5 +1 on this request.

**Comment by JeffGiroux** [comment]
I also have a need. Here is my sample bgp stuff in tmsh commands.

tmsh create net routing bgp 65530 local-as 65530 neighbor add { 10.255.255.4 { remote-as 65515 ebgp-multihop 2 } 10.255.255.5 { remote-as 65515 ebgp-multihop 2 } } address-family { ipv4 { redistribute add { kernel } aggregate-address add { 10.0.0.0/16 { summary-only enabled } 10.1.0.0/16 { summary-only enabled } 10.2.0.0/16 { summary-only enabled } 10.3.0.0/16 { summary-only enabled } } } } graceful-restart { restart-time 120 }

**Comment by dstokesf5** [comment]
It looks like this GitHub issue was not updated when this functionality was released: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/declarations/network-objects.html#configuring-bgp-routing-in-a-declaration

There are a lot of parts that can be configured with bgp routing, and DO does not expose all of them yet. If you find something is missing for your use case, please file a new GitHub issue.
