### ISSUE TITLE
Support for ldaps in authentication_ldap

### ISSUE THREAD

**Issue by kwinkelman-bw** [F5Networks/f5-declarative-onboarding#126]
### Is your feature request related to a problem? Please describe.
DO does not seem to support ldaps (ldap over ssl/port 636). Without this support we are configuring our BIG-IP to pass plaintext credentials over the network, which is not the desired security posture. I've looked at the documentation and the auth schema in this repo with no luck.

### Describe the solution you'd like
DO should have a parameter in the ldap configuration to support SSL in the same way that the tmsh and webui do.

**Comment by dstokesf5** [comment]
To help us make sure we are on the same page with this feature request, can you provide some example tmsh configuration for what you are trying to achieve?

**Comment by kwinkelman-bw** [comment]
Here's an example:
`auth ldap system-auth {
    bind-dn <redacted>
    bind-pw <redacted>
    check-roles-group enabled
    login-attribute uid
    port ldaps
    search-base-dn <redacted>
    servers { <redacted> }
    ssl enabled
}`

**Comment by dstokesf5** [comment]
Thank you, that is very helpful. Do you need any of the following ssl settings as well?
* ssl
* ssl-ca-cert-file
* ssl-check-peer
* ssl-ciphers
* ssl-client-cert
* ssl-client-key

**Comment by kwinkelman-bw** [comment]
Took a look at our configs and I don't see those found anywhere - so I do not think we need them to duplicate our current authentication settings with DO. 

However I'd always want to argue for feature parity. Can't predict the future need.

**Comment by sporky** [comment]
@dstokesf5  I am working with a customer that does require ssl-check-peer and ssl-ca-cert-file.  They would appreciate those options being included.

**Comment by dstokesf5** [comment]
@kwinkelman-bw @sporky Thanks for your input. I have added AUTOTOOL-1380 to our internal product back log to configure the ssl properties with DO.

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 1.13.0 release.
