### ISSUE TITLE
Ability to create self-signed certificate/key or import certificate/key to apply to httpd crt/key and/or big3d client.crt and/or gtm server.crt

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-declarative-onboarding#127]
### Is your feature request related to a problem? Please describe.
As part of our initial builds a self-signed certificate/key is created and applied to use for httpd, big3d, and gtm server certificates. 

### Describe the solution you'd like
Ability to either create a self-signed cert/key or import an external cert/key to place for the httpd, big3d, or gtm certificates

### Describe alternatives you've considered
Using Ansible create a Cert/Key manually using openssl, then placing the cert onto the appropriate directories.

### Additional context

Example of either via bash or command sent via Ansible:

- openssl   req -x509 -nodes -days 3650 -newkey rsa:2048 -subj   "/C=US/ST=OH/L=Columbus/O=My Company/OU=Network Team/CN=`uname -n`" -keyout /config/httpd/conf/ssl.key/server.key   -out /config/httpd/conf/ssl.crt/server.crt -sha256

- cat   /config/httpd/conf/ssl.crt/server.crt > /config/big3d/client.crt

- cat   /config/httpd/conf/ssl.crt/server.crt > /config/gtm/server.crt

--

--

--

**Comment by dstokesf5** [comment]
We have AUTOTOOL-152 in our internal product backlog to configure the certificate used by httpd.

**Comment by dstokesf5** [comment]
This was resolved in the 1.12.0 release.
