### ISSUE TITLE
Ability to set multicast-ip when defining failover network for a device

### ISSUE THREAD

**Issue by LeonardosGitHub** [F5Networks/f5-declarative-onboarding#128]
### Is your feature request related to a problem? Please describe.

I would like the ability to set the multicast address, interface, and port at Device Management > Devices > {{big_ip}} > Failover Network > Failover Multicast Configuration.

### Describe the solution you'd like

Similar to setting a Config Sync (class:ConfigSync) and Failover Unicast address(class:FailoverUnicast) that is already found on Declarative Onboarding, I'd like to be able to set the Multicast information as well.

### Additional context

modify cm device guest2.example.com multicast-ip 224.0.0.2 multicast-port 62960 multicast-interface eth0

**Comment by dstokesf5** [comment]
Thank you for your feedback. This is being tracked internally as AUTOTOOL-1373.

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.17.0 release.
