### ISSUE TITLE
device group "f5test-ha-dg" not found

### ISSUE THREAD

**Issue by kurri-arjun** [F5Networks/f5-declarative-onboarding#138]
### Environment
 * Declarative Onboarding Version: 1.11.0.1
 * BIG-IP Version: 14.1.2.2.

### Summary
The device group used to setup HA for BIGIP in declaration was not found for configuration sync

### Steps To Reproduce
1. Two BIGIPs configured with mgmt and self ips.
2. Installed RPM against BIGIPs
3. Executed HA declarations against two BIGIPs(PFA declarations)
4. They do configuration sync

### Expected Behavior
Configuration sync should be successful.

### Actual Behavior
Getting exception : "Configuration error: Device group (f5test-ha-dg) not found in device group sync
[Dec1.txt](https://github.com/F5Networks/f5-declarative-onboarding/files/4448376/Dec1.txt)
[Dec2.txt](https://github.com/F5Networks/f5-declarative-onboarding/files/4448378/Dec2.txt)

"

**Comment by dstokesf5** [comment]
In our previous discussion, it was mentioned that both declarations were successful, but the f5test-ha-dg could not be found when inspecting the BIG-IP config. Is that still what you are seeing here?

I have noticed that the config sync and failover addresses in Dec1 are odd. They usually reference a self-ip on the device that you are applying the declaration to, but yours seem to be referring to the other device in the cluster. Can you try updating Dec1 to reference the sefl-ip of the device you are configuring to see if that resolves your issue?

If that does not help, then I could use some additional information as I try to reproduce this issue:
* What environment are you running in? Hardware, Azure, Openstack?
* How many interfaces do your devices have?

**Comment by dstokesf5** [comment]
I have been able to reproduce this failure intermittently, and I have added it to our internal product backlog as AUTOTOOL-1491.

**Comment by dstokesf5** [comment]
While looking into this, one of our developers noticed that there was no hostnames specified in the provided declarations. Are both devices using the default hostname, or are you setting it via some other method (e.g. dhcp)?

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 1.13.0 release.
