### ISSUE TITLE
Cluster re-run can't form device trust

### ISSUE THREAD

**Issue by garyluf5** [F5Networks/f5-declarative-onboarding#14]
When I initially run my [cluster onboarding json](https://github.com/garyluf5/f5_terraform/blob/master/Azure_Secure_Enclave_Public_DMZ/cluster.json) on both BIGIP VE, they can form the HA and the DSC. However, if I destroy one of the VEs, and rerun the same same cluster onboarding script, they never ended up forming the HA in the same DSC. I suspect there maybe a "device trust reset" needed in order to have this working.

I have tried on either BIG-IP VE, still have the same result, so it doesn't matter who is "owner"

**Comment by seattlevine** [comment]
Thanks - will investigate.

Tracking w/ internal issue 233

**Comment by seattlevine** [comment]
Possibly related this comment from internal channel:
Tue, 19 Mar 2019 00:32:38 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: retryOrReject: numRemaining: 200 , code: 404 , message: tryUntil: max tries reached: 01020036:3: The requested device group (/Common/failoverGroup) was not found.

They were in an ha pair created by do, and then I manually reset device trust on both devices, and sent the previously used declaeation.

**Comment by focrensh** [comment]
New internal ticket of AT-90.

**Comment by seattlevine** [comment]
Resolved in 1.5.0
