### ISSUE TITLE
resubmitting feature request: Add support for auth partitions with route domains

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/f5-declarative-onboarding#141]
### Is your feature request related to a problem? Please describe.
This was originally filed under issue #51 but closed. I'd like to re-open because we have a few SE's and SA's that would need this. Here's our situation: we are deploying BIG-IPs into AWS across different AZ's. Then we want to use DO to configure the devices and cluster them. Because they are in different AZ's, we need to create a default route that is unique to each of the devices, and therefore it should be created in a LOCAL_ONLY partition that is not sync'd between devices. So, we need DO to be able to create auth partitions and we need to be able to define a route in this partition. 

### Describe the solution you'd like
Ideally we'd like to be able to use DO to configure the devices and cluster them, even when the devices are in separate subnets and across AZ's.  So we need DO to support auth partitions with route domains.

### Describe alternatives you've considered
Because we cannot use DO to create routes that are not in /Common, we have resorted to BASH commands in the onboarding script run at deployment time in AWS. However this is not ideal.

### Additional context
This is a public-facing guide to setting up HA in AWS and it states that you need a LOCAL_ONLY partition: https://www.f5.com/pdf/deployment-guides/f5-aws-ha-dg.pdf (see the step "Creating a new partition")

**Comment by s-archer** [comment]
+1 
I had to add the following commands to user-data to achieve this. 

tmsh create net vlan internal { interfaces add { 1.2 } tag 1002 }
tmsh create net self internal-self { address ${internal_ip}/24 allow-service default traffic-group traffic-group-local-only vlan internal }
# command below creates a partition in addition to a folder, automatically.
tmsh create sys folder /LOCAL_ONLY device-group none traffic-group traffic-group-local-only
tmsh -q -c 'cd /LOCAL_ONLY; create net route default { gw ${internal_gw} network default }'
tmsh save sys config partitions all

**Comment by dstokesf5** [comment]
Would a flag on the Route class to create the route in LOCAL_ONLY satisfy your use case? To avoid scope conflict with AS3 we would rather not allow arbitrary create of auth partitions with Declarative Onboarding.

**Comment by mikeoleary** [comment]
@dstokesf5 thanks and understood. I think so. The flag would need to create the partition as well as the route in that partition (ie, the partition will not exist prior to the DO declaration). This should allow us to configure a HA-pair across AZ's in AWS.

**Comment by dstokesf5** [comment]
@mikeoleary Excellent. That is what we are planning to do with AUTOTOOL-1749.

**Comment by dstokesf5** [comment]
This issue should be resolved in the 1.15.0 release.
