### ISSUE TITLE
JSHINT issues encountered in file restWorker.js

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-declarative-onboarding#145]
### Environment
 * Declarative Onboarding Version: 1.13
 * BIG-IP Version: 15.1.0.2

### Summary
Checking logs and saw the following:
```
[azureuser@localhost:Active:Standalone] restnoded # cat restnoded.log | grep declar
Thu, 04 Jun 2020 05:38:55 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js
Thu, 04 Jun 2020 05:38:55 GMT - severe: [LoaderWorker] JSHINT issues encountered in file /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js, 1 error
Thu, 04 Jun 2020 05:38:55 GMT - severe: [LoaderWorker] /var/config/rest/iapps/f5-declarative-onboarding/nodejs/restWorker.js: line 1199, col 41, If a strict mode function is executed using function invocation, its 'this' value will be undefined.
Thu, 04 Jun 2020 05:38:56 GMT - info: [f5-declarative-onboarding: restWorker.js] Created Declarative onboarding worker
Thu, 04 Jun 2020 05:38:56 GMT - info: starting /shared/declarative-onboarding
Thu, 04 Jun 2020 05:38:56 GMT - info: [WorkerStateManager] Storage worker reports no key for: /shared/declarative-onboarding
Thu, 04 Jun 2020 05:38:56 GMT - info: [f5-declarative-onboarding: doUtil.js] Platform: BIG-IP
Thu, 04 Jun 2020 05:38:56 GMT - info: [f5-declarative-onboarding: restWorker.js] Initial startup
Thu, 04 Jun 2020 05:38:56 GMT - config: [RestWorker] /shared/declarative-onboarding has started. Name:RestWorker
Thu, 04 Jun 2020 05:38:56 GMT - finest: [restnodedOdataAdapter] Forwarder notify callback: {"external":"/mgmt/shared/declarative-onboarding","internal":"/shared/declarative-onboarding","port":8105,"apiStatus":"NO_STATUS"}
```

### Steps To Reproduce
1. deploy new VE, install DO RPM
2. check logs

Repo for testing = https://github.com/JeffGiroux/f5_terraform/tree/master/Azure/HA_via_api

Did not push DO declaration yet.

### Expected Behavior
n/a

### Actual Behavior
I'm not sure if this is causing issues or not. Currently not seeing anything with POSTing the DO declaration when it actually takes. However, i have had multiple deployment attempts where terraform sends CURL to POST DO and I don't get a response back...as if DO isn't ready yet or endpoint doesn't exist. If that was the case, I would assume the restnoded would have a related log saying endpoint doesn't exist. Normal behavior is to get a 202:running response from DO when I POST. Not sure if the issue with restWorker.js JSHINT error and my DO issue are related.

**Comment by dstokesf5** [comment]
The JSHINT errors do not prevent Declarative Onboarding from starting or functioning normally. However, we are cleaning them up to avoid any further confusion.
