### ISSUE TITLE
GET to empty declaration responds with 500 error instead of 204 no content

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-declarative-onboarding#148]
### Environment
 * Declarative Onboarding Version: 1.13.0
 * BIG-IP Version: 15.1.0.2

### Summary
I have validation scripts to check /info and /declare for all the Automation Toolchain extensions during my BIG-IP startup onboarding. When I validate a GET on DO /declare to a device with no declaration, I receive a 500 error from BIG-IP.

### Steps To Reproduce
1. Start with fresh device and perform GET to https://{{bigip_mgmt}}/mgmt/shared/declarative-onboarding/declare

2. Observe the following error response:
```
{
    "code": 500,
    "message": "No responder for endpoint: declare",
    "referer": "68.3.20.23",
    "originalRequestBody": "",
    "errorStack": []
}
```

### Expected Behavior
I would like DO to match the behavior of AS3 when checking an empty declaration. For example, when you do GET to /declare on AS3 with no declaration then you receive an empty payload response with "204 No Content".

### Actual Behavior
When I GET /declare on DO, I receive 500 error.

**Comment by dstokesf5** [comment]
The Declarative Onboarding extension has no /declare endpoint: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/http-methods.html
