### ISSUE TITLE
Remote-Role Variable Substitution Missing

### ISSUE THREAD

**Issue by NicCage1337** [F5Networks/f5-declarative-onboarding#156]
### Is your feature request related to a problem? Please describe.
The DO Declaration does not except Variable Substition of remote-role fields as described in 
https://techdocs.f5.com/en-us/bigip-15-0-0/big-ip-systems-user-account-administration/remote-user-account-management.html#GUID-214EDA81-E145-45E1-B552-6B9C3A0F3C3F (Section "About Variable Substitution")

Example Error Message:
`Thu, 06 Aug 2020 12:39:56 GMT - info: [f5-declarative-onboarding: restWorker.js] Bad declaration: [{"keyword":"enum","dataPath":".declaration.Common['Guest'].console","schemaPath":"#/definitions/remoteAuthRole/properties/console/enum","params":{"allowedValues":["disabled","tmsh"]},"message":"should be equal to one of the allowed values"},{"keyword":"oneOf","dataPath":".declaration.Common['Guest']","schemaPath":"#/allOf/0/then/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"}]`

Piece of the Declaration:
...
"Guest": {
            "class": "RemoteAuthRole",
            "attribute": "F5-LTM-User-Info-1=Guest",
            "console": "%F5-LTM-User-Shell",
            "lineOrder": 1009,
            "role": "%F5-LTM-User-Role",
            "remoteAccess": false,
            "userPartition": "%F5-LTM-User-Partition"
        }
...

### Describe the solution you'd like
As per the documentation the Parser should except values starting with %, as the correspond with Variables defined on the AAA System.
On a working system the Config Block looks like this:
        Guest {
            attribute F5-LTM-User-Info-1=Guest
            console %F5-LTM-User-Shell
            line-order 1009
            role %F5-LTM-User-Role
            user-partition %F5-LTM-User-Partition
        }

### Describe alternatives you've considered
An alternative is to configure the remote-roles once the DO Declaration has been processed with the Scripting / Automation Engine of your choice

**Comment by dstokesf5** [comment]
This has been added to our internal product backlog as AUTOTOOL-1943.

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.17.0 release.
