### ISSUE TITLE
DeviceCertificate not installed 

### ISSUE THREAD

**Issue by focrensh** [F5Networks/f5-declarative-onboarding#158]
### Environment
 * Declarative Onboarding Version: 1.8
 * BIG-IP Version: 14.1.2.2

### Summary
When including the DeviceCertificate class within the declaration, the device crt/key do not seem to be updated. I am not seeing any errors pertaining to this in the restnoded logs.

I am not seeing the backed up original crt/key in the directories or the current files being updated:
/config/httpd/conf/ssl.key/server.key
/config/httpd/conf/ssl.crt/server.crt

I am happy to provide my crt/key if needed internally. It does not seem to be specific to them though.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "schemaVersion": "1.6.0",
    "class": "Device",
	"async": true,
    "Common": {
        "class": "Tenant",
        "deviceCertificate": {
            "class": "DeviceCertificate",
            "certificate": {
                "base64": "CRT"
            },
            "privateKey": {
                "base64": "KEY"
            }
        }
    }
}
```

2. Observe the following error response:
```json
    "result": {
        "class": "Result",
        "code": 200,
        "status": "OK",
        "message": "success"
    }
```

### Expected Behavior
The following files are updated on BIG-IP:

/config/httpd/conf/ssl.key/server.key
/config/httpd/conf/ssl.crt/server.crt

### Actual Behavior
Success message but no change.

**Comment by dstokesf5** [comment]
Thank you for reporting this. I have added it to our internal product backlog as AUTOTOOL-1878.

**Comment by dstokesf5** [comment]
@focrensh I hear you are no longer experiencing this issue. Can we close it?

**Comment by focrensh** [comment]
Yes, thanks. Issue is resolved in current version.
