### ISSUE TITLE
License BIG-IP via  activate.f5.com using DO example

### ISSUE THREAD

**Issue by grmarxer** [F5Networks/f5-declarative-onboarding#161]
I understand that DO supports licensing BIG-IP directly via regkey to activate.f5.com.  However, no example exists.  The only examples are licensing BIG-IP from BIG-IQ.  Please provide an example for activating and reactivating a license without BIG-IQ license manager

**Comment by dstokesf5** [comment]
The standalone BIG-IP example declarations contains an example of simple regkey based licensing: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/bigip-examples.html

Does this example work for you?

**Comment by grmarxer** [comment]
Yes, that works for me.  However a separate example should be created so other customers do not struggle looking for the same information.

**Comment by dstokesf5** [comment]
Since an example exists, I am closing this issue. However, I did add AUTOTOOL-2047 to our internal product backlog to review the large example declarations and how we can make it easier for users to find the information they need.
