### ISSUE TITLE
GTM/DNS Sync

### ISSUE THREAD

**Issue by jtylershaw** [F5Networks/f5-declarative-onboarding#162]
### Describe the solution you'd like
We need the ability within DO to add/remove a device from a GTM/DNS sync group.  This can already be done via Ansible, but the preferred solution would be to have it in DO.

Along with this, setting the parameters of Sync Group Name and synchronize zone files will be key in setting up the device to be joined into a sync group (see https://support.f5.com/csp/article/K14044).  

### Describe alternatives you've considered
This can be done via other tools, operating directly against the API, but DO is the ideal place for this to live.

### Additional context
The rest of the key values for setting up a sync group are found in this document:  https://support.f5.com/csp/article/K13734 and can be accomplished through DO currently, aside from the possibility of installing the correct big3d if the versions are incompatible.  This should be one of the assumptions when delivering this feature that all versions between LTM & DNS are the same and if there is a difference then that should be a separate development.

**Comment by delgadillo22** [comment]
Thank you for your request. It's been added to our internal backlog as https://jira.pdsea.f5net.com/browse/AUTOTOOL-1937 for research and sizing.

**Comment by mdditt2000** [comment]
Jira EPIC AUTOTOOL-1937 task is closed as implemented
--
Resolved in https://github.com/F5Networks/f5-declarative-onboarding/releases/tag/v1.17.0
