### ISSUE TITLE
"Allow" attribute schema should be same for HTTPD and SSHD classes

### ISSUE THREAD

**Issue by vjeedimalla** [F5Networks/f5-declarative-onboarding#163]
### Is your feature request related to a problem? Please describe.
when you observe "Allow" field schema of both HTTPD and SSHD, the end result is same. Both supports either “none” or “all” or “array of ip addresses”. In case of HTTPD “all” is clubbed with “ipaddress” as one of them whereas in SSHD “all” is clubbed with “none” as one of them. When both supports same values why they have different schema. 

Because of this schema validation and any UI component generation is not consistent for both classes even though they are same for "allow" field. 

### Describe the solution you'd like
 think adding “all” to “none” should work. And to avoid backward breaking continue “all” in second section of “oneOf” as well.  
 **const: “none” should be enum: [ “none”, “all”]**

**Comment by dstokesf5** [comment]
Thank you for your feedback, the issue has been added to our internal product backlog as AUTOTOOL-1924.

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.17.0 release.
