### ISSUE TITLE
Received error "double quotes are not balanced" when using DO v1.14.0 POST deviceCertificate

### ISSUE THREAD

**Issue by iamtzar** [F5Networks/f5-declarative-onboarding#164]
### Environment
 * Declarative Onboarding Version: 1.14.0 and 1.15.0
 * BIG-IP Version: v14.1.2.7

### Summary
Received error "double quotes are not balanced" when using DO v1.14.0 POST deviceCertificate

### Steps To Reproduce
The request - payload-czar.json is shown as below:

> {
>     "schemaVersion": "1.14.0",
>     "async": true,
>     "class": "Device",
>     "label": "f5_vmnn DO Definition",
>     "Common": {
>         "class": "Tenant",
>         "hostname": "czar-test.com",
>         "deviceCertificate": {
>             "class": "DeviceCertificate",
>             "certificate": {
>                 "base64": "F5fakecerTdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ5RENDQXR3Q0NRQ0x2QUZoZVJaRlNqQU5CZ2txaGtpRzl3MEJBUXNGQURDQnV6RUxNQWtHQTFVRUJoTUMKVlZNeEV6QVJCZ05WQkFnTUNsZGhjMmhwYm1kMGIyNHhFREFPQmdOVkJBY01CMU5sWVhSMGJHVXhDekFKQmdOVgpCQW9NQWtZMU1SOHdIUVlEVlFRTERCWkVaV05zWVhKaGRHbDJaU0JQYm1KdllYSmthVzVuTVNZd0pBWURWUVFECkRCMW1OUzFrWldOc1lYSmhkR2wyWlMxdmJtSnZjbUZrYVc1bkxtTnZiVEV2TUMwR0NTcUdTSWIzRFFFSkFSWWcKYldWQVpqVXRaR1ZqYkdGeVlYUnBkbVV0YjI1aWIyRnlaR2x1Wnk1amIyMHdIaGNOTVRrd01UQTBNakV3T1RRNApXaGNOTWpBd01UQTBNakV3T1RRNFdqQ0J1ekVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnTUNsZGhjMmhwCmJtZDBiMjR4RURBT0JnTlZCQWNNQjFObFlYUjBiR1V4Q3pBSkJnTlZCQW9NQWtZMU1SOHdIUVlEVlFRTERCWkUKWldOc1lYSmhkR2wyWlNCUGJtSnZZWEprYVc1bk1TWXdKQVlEVlFRRERCMW1OUzFrWldOc1lYSmhkR2wyWlMxdgpibUp2Y21Ga2FXNW5MbU52YlRFdk1DMEdDU3FHU0liM0RRRUpBUllnYldWQVpqVXRaR1ZqYkdGeVlYUnBkbVV0CmIyNWliMkZ5WkdsdVp5NWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG0KZGUxQkRKOEdReWhqSHZTTjJ5TThDOTZjT1VuS0NRVWs2d2JKRFRQME1RNEJYUnhFVUJFTjhwOHFTN3FSaDdQcQpvVWt2enVBYVl0cGlxcjZLb0tSWXRobVFwYlBIVXFmckZDVUs0TjB0L29YdjdhY0x1SEVuYW1OZmlrYU5VVTZDClh0TlZFUmZwZTlmU21kRTlzVCtKTDRPNWNpc1RCcWlESGIwaWpOa1lSMHE2cHEwdEpkZGtGNTZ1bGo2WUtOazUKb3EzTVBUeENGQzJCVFRIcmc1N0tMeTdwZjZUL0NjUHk5ZDBSUC81K2NyK1o0NjVTMitEYVBZR3dvQzdKd1RZQgo1L0doelpwc1ovQVN0ZjdwYnJuSVFLVW5pSk1pNjhVZURZWXpyYjhYYjAzeHVNMHE5bXhhS01Hd0VCd2ZKWmZ1CjhZaDFXL1VFYS9Ic3pYNklDSFhqQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ1o4NzNYcHdJaHIKd0dVTGZTYWpqeWdvUXZzOFRPQ2N5YWUwTnl3emw0NEE5VVZsUTVJZVpWVzdyYk1BUDhTMkh4RnJzSmk2VCthNQphSFFsc09jeWZGZ3Q1MHoyRXhvekJIcFY3eHNUb3JMTGx4RUpqMk55RnA1OXIrZXhEVnhPMHUwbTRjR2xiVUVKCndZZEQ5VkFTWTZlZ1QrWXkzaVlMK0NWdmpJQk9wRC8zaDBmOHB2TjJlek02MGE3L0FNWnRyRzNuSXlUZkJZMkcKOG5NdUY1Qk5vTFAzNFVQOUJDeE5LMi8zR2YwNHFyNDk2MnVCbHQ0UjJNR3N4enZGS1JIb2JJRm9XbkpQMWVXbApzQVhzajlUVit1UVFPb2xXdG1xUE5qVGNIc2V2am9EdUpUMjRudzU0TUs0bVg4eXlJbEkyNERvYlhFMEJNK2hoCkhWS0xmT1o0TWYwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
>             },
>             "privateKey": {
>                 "base64": "F5fakeKeyJTiBioQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRG1kZTFCREo4R1F5aGoKSHZTTjJ5TThDOTZjT1VuS0NRVWs2d2JKRFRQME1RNEJYUnhFVUJFTjhwOHFTN3FSaDdQcW9Va3Z6dUFhWXRwaQpxcjZLb0tSWXRobVFwYlBIVXFmckZDVUs0TjB0L29YdjdhY0x1SEVuYW1OZmlrYU5VVTZDWHROVkVSZnBlOWZTCm1kRTlzVCtKTDRPNWNpc1RCcWlESGIwaWpOa1lSMHE2cHEwdEpkZGtGNTZ1bGo2WUtOazVvcTNNUFR4Q0ZDMkIKVFRIcmc1N0tMeTdwZjZUL0NjUHk5ZDBSUC81K2NyK1o0NjVTMitEYVBZR3dvQzdKd1RZQjUvR2h6WnBzWi9BUwp0ZjdwYnJuSVFLVW5pSk1pNjhVZURZWXpyYjhYYjAzeHVNMHE5bXhhS01Hd0VCd2ZKWmZ1OFloMVcvVUVhL0hzCnpYNklDSFhqQWdNQkFBRUNnZ0VBWDFOQUE3d1l1eHBrUmp1enBFbVVWVzREY2xNdjltV3N2d3lJRGZsc0dBR0MKYllYNS96ZXZGam5aSkVHV3RrT1BZK202d0ErdUdydnc0UWNITVlnbzhwakFFbGkzK0NaMFZvUktuaWxNMDQySQpFU29ZQW4wVU1OMk1wU1FvOHFOQytpSUhBQlRGODBuS2g4NGdBb2lpWXpoSUlCamRRRTFzdm04Nm9HUHFHR1A3CnlYcFNiWXNHOElVSzVNcGRObjBXWkR6eGRiTGhCZFhWSHd0ZENaWm9Vak5FbjZSeUUrVlBjWjUxRW9vbFZPY20KZVRKMEs0YzRZa2E0cnJYbzlMYWYxbXRIcEdMYVVPbDRQQkU3eWRpbnJsZElkU05Ddnd0VlNJR0RzOG9vNGZZYQpiVmVRNDNkQ2dxVWN0ejNYRC9mZ1FFTGxGR2ptRXRYb04zcm56L1g0NFFLQmdRRDI5R2RzR2dBbVN2U21RSVJ2CldyNmdVYUg2VFQvelBiUnNRcjkvZmtyVVp4UHp1TTJzc1NkcjlyNnZOalliQlZ3alQ2T0piclBXUzJSdmwvZ0QKY2JqNm5uNzNKZ3k5Q0k1SmFuOGRoRkxaa3MrU2h1YmZ6OHdaTWwyUmd4UVN6UEhBeWJoa0xhNjY2eG5WRER4QQp4clYrYzZOZVp2OVBjS3NwRVllTHJac1F0UUtCZ1FEdTV0MVh2YS9VYkFQR0ltVUwzRVl0UWxRaE5QdzlWb0hnCkdSMHo2T2JnY1IvdEtGL29JaVdOSlA2UkovNUsvQ21VVVBjNXpMM2xFank3QXdaMVc1WkNsK3pvRFcxbENxcDEKbkdDQ2ViclJYMnRYbzFxbHFvMkVoZVZCRHVnTXAwWmxmM2dpbjcrSXNjOWEraFRGSGVXZGJZYU1wNnZXVHlkMwpMSnhZcXNiRE53S0JnUURnZkM3L1QydFBZOWVjd1EwaUJFVkFpclJKU2F1V08wTWxIay9oWHpZNmVqRGkzZHpvCjNHalBkWTdFeXV6SUIwbElOLzZhMFd6Y29jLzh1UklVWDI0ZE03S0tpNllNdUJoUG1HVlF1Wlp1ZlV2L0VHNFMKaVZ3b2syWUcvalpqR0xXeDRDeWpzL3Nmb3RMcW5hS3Y1M0hZTHRvVTJGL0JJTlFXRXY4NTgyZi8rUUtCZ0NSNQpqeFhVV2tJZWM3ME9oMHIyU0tpa1ZkLzBEUWI0YkQvZzFicVZOcHJSNnNQMHhCL1hCdEN6ODBJS1R5TDN1UWx5CkN5MEIrNFE3OHBYQzhudDhqa2FBbDZVZVY3TnptMjcxZnk2c2t6OWdTQzFMUFkzSnFtMnZXNzlCSFdEQk1WaFIKeSsvTllCcm91dlh5OUxUYnliRHRoZnQzcGg3RVd3d3cvWFgwTFFDbEFvR0JBTUFSWHpoT0RsdTV3TFdHRlpQdApJUGF1VG05UWhjNH"
>             }
>         }
>     }
> }

1. Sending request:

> # curl -sku $CREDS -H "Content-Type: application/json" -X POST https://$IPA/mgmt/shared/declarative-onboarding -d @payload-czar.json | js-beautify
> {
>     "id": "296ac9ff-870a-4f3c-b47d-6356c46b9470",
>     "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/296ac9ff-870a-4f3c-b47d-6356c46b9470",
>     "result": {
>         "class": "Result",
>         "code": 202,
>         "status": "RUNNING",
>         "message": "processing"
>     },
>     "declaration": {
>         "schemaVersion": "1.14.0",
>         "async": true,
>         "class": "Device",
>         "label": "f5_vmnn DO Definition",
>         "Common": {
>             "class": "Tenant",
>             "hostname": "czar-test.com",
>             "deviceCertificate": {
>                 "class": "DeviceCertificate",
>                 "certificate": {
>                     "base64": "F5fakecerTdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ5RENDQXR3Q0NRQ0x2QUZoZVJaRlNqQU5CZ2txaGtpRzl3MEJBUXNGQURDQnV6RUxNQWtHQTFVRUJoTUMKVlZNeEV6QVJCZ05WQkFnTUNsZGhjMmhwYm1kMGIyNHhFREFPQmdOVkJBY01CMU5sWVhSMGJHVXhDekFKQmdOVgpCQW9NQWtZMU1SOHdIUVlEVlFRTERCWkVaV05zWVhKaGRHbDJaU0JQYm1KdllYSmthVzVuTVNZd0pBWURWUVFECkRCMW1OUzFrWldOc1lYSmhkR2wyWlMxdmJtSnZjbUZrYVc1bkxtTnZiVEV2TUMwR0NTcUdTSWIzRFFFSkFSWWcKYldWQVpqVXRaR1ZqYkdGeVlYUnBkbVV0YjI1aWIyRnlaR2x1Wnk1amIyMHdIaGNOTVRrd01UQTBNakV3T1RRNApXaGNOTWpBd01UQTBNakV3T1RRNFdqQ0J1ekVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnTUNsZGhjMmhwCmJtZDBiMjR4RURBT0JnTlZCQWNNQjFObFlYUjBiR1V4Q3pBSkJnTlZCQW9NQWtZMU1SOHdIUVlEVlFRTERCWkUKWldOc1lYSmhkR2wyWlNCUGJtSnZZWEprYVc1bk1TWXdKQVlEVlFRRERCMW1OUzFrWldOc1lYSmhkR2wyWlMxdgpibUp2Y21Ga2FXNW5MbU52YlRFdk1DMEdDU3FHU0liM0RRRUpBUllnYldWQVpqVXRaR1ZqYkdGeVlYUnBkbVV0CmIyNWliMkZ5WkdsdVp5NWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG0KZGUxQkRKOEdReWhqSHZTTjJ5TThDOTZjT1VuS0NRVWs2d2JKRFRQME1RNEJYUnhFVUJFTjhwOHFTN3FSaDdQcQpvVWt2enVBYVl0cGlxcjZLb0tSWXRobVFwYlBIVXFmckZDVUs0TjB0L29YdjdhY0x1SEVuYW1OZmlrYU5VVTZDClh0TlZFUmZwZTlmU21kRTlzVCtKTDRPNWNpc1RCcWlESGIwaWpOa1lSMHE2cHEwdEpkZGtGNTZ1bGo2WUtOazUKb3EzTVBUeENGQzJCVFRIcmc1N0tMeTdwZjZUL0NjUHk5ZDBSUC81K2NyK1o0NjVTMitEYVBZR3dvQzdKd1RZQgo1L0doelpwc1ovQVN0ZjdwYnJuSVFLVW5pSk1pNjhVZURZWXpyYjhYYjAzeHVNMHE5bXhhS01Hd0VCd2ZKWmZ1CjhZaDFXL1VFYS9Ic3pYNklDSFhqQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ1o4NzNYcHdJaHIKd0dVTGZTYWpqeWdvUXZzOFRPQ2N5YWUwTnl3emw0NEE5VVZsUTVJZVpWVzdyYk1BUDhTMkh4RnJzSmk2VCthNQphSFFsc09jeWZGZ3Q1MHoyRXhvekJIcFY3eHNUb3JMTGx4RUpqMk55RnA1OXIrZXhEVnhPMHUwbTRjR2xiVUVKCndZZEQ5VkFTWTZlZ1QrWXkzaVlMK0NWdmpJQk9wRC8zaDBmOHB2TjJlek02MGE3L0FNWnRyRzNuSXlUZkJZMkcKOG5NdUY1Qk5vTFAzNFVQOUJDeE5LMi8zR2YwNHFyNDk2MnVCbHQ0UjJNR3N4enZGS1JIb2JJRm9XbkpQMWVXbApzQVhzajlUVit1UVFPb2xXdG1xUE5qVGNIc2V2am9EdUpUMjRudzU0TUs0bVg4eXlJbEkyNERvYlhFMEJNK2hoCkhWS0xmT1o0TWYwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
>                 }
>             }
>         }
>     }
> }

---------------
Note: The request has a long-running asynchronous job to a REST API thus API returned 202 RUNNING, processing...
Now I am sending a HTTP GET request to URI /mgmt/shared/declarative-onboarding/task/296ac9ff-870a-4f3c-b47d-6356c46b9470 periodically for completion status of the job.
---------------

2. Checking response:

> # curl -sku $CREDS -H "Content-Type: application/json" -X GET https://$IPA/mgmt/shared/declarative-onboarding/task/296ac9ff-870a-4f3c-b47d-6356c46b9470 | js-beautify
> {
>     "id": "296ac9ff-870a-4f3c-b47d-6356c46b9470",
>     "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/296ac9ff-870a-4f3c-b47d-6356c46b9470",
>     "code": 422,
>     "status": "ERROR",
>     "message": "invalid config - rolled back",
>     "errors": ["double quotes are not balanced", "double quotes are not balanced"],
>     "result": {
>         "class": "Result",
>         "code": 422,
>         "status": "ERROR",
>         "message": "invalid config - rolled back",
>         "errors": ["double quotes are not balanced", "double quotes are not balanced"]
>     },
>     "declaration": {
>         "schemaVersion": "1.14.0",
>         "async": true,
>         "class": "Device",
>         "label": "f5_vmnn DO Definition",
>         "Common": {
>             "class": "Tenant",
>             "hostname": "czar-test.com",
>             "deviceCertificate": {
>                 "class": "DeviceCertificate",
>                 "certificate": {
>                     "base64": "F5fakecerTdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ5RENDQXR3Q0NRQ0x2QUZoZVJaRlNqQU5CZ2txaGtpRzl3MEJBUXNGQURDQnV6RUxNQWtHQTFVRUJoTUMKVlZNeEV6QVJCZ05WQkFnTUNsZGhjMmhwYm1kMGIyNHhFREFPQmdOVkJBY01CMU5sWVhSMGJHVXhDekFKQmdOVgpCQW9NQWtZMU1SOHdIUVlEVlFRTERCWkVaV05zWVhKaGRHbDJaU0JQYm1KdllYSmthVzVuTVNZd0pBWURWUVFECkRCMW1OUzFrWldOc1lYSmhkR2wyWlMxdmJtSnZjbUZrYVc1bkxtTnZiVEV2TUMwR0NTcUdTSWIzRFFFSkFSWWcKYldWQVpqVXRaR1ZqYkdGeVlYUnBkbVV0YjI1aWIyRnlaR2x1Wnk1amIyMHdIaGNOTVRrd01UQTBNakV3T1RRNApXaGNOTWpBd01UQTBNakV3T1RRNFdqQ0J1ekVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnTUNsZGhjMmhwCmJtZDBiMjR4RURBT0JnTlZCQWNNQjFObFlYUjBiR1V4Q3pBSkJnTlZCQW9NQWtZMU1SOHdIUVlEVlFRTERCWkUKWldOc1lYSmhkR2wyWlNCUGJtSnZZWEprYVc1bk1TWXdKQVlEVlFRRERCMW1OUzFrWldOc1lYSmhkR2wyWlMxdgpibUp2Y21Ga2FXNW5MbU52YlRFdk1DMEdDU3FHU0liM0RRRUpBUllnYldWQVpqVXRaR1ZqYkdGeVlYUnBkbVV0CmIyNWliMkZ5WkdsdVp5NWpiMjB3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG0KZGUxQkRKOEdReWhqSHZTTjJ5TThDOTZjT1VuS0NRVWs2d2JKRFRQME1RNEJYUnhFVUJFTjhwOHFTN3FSaDdQcQpvVWt2enVBYVl0cGlxcjZLb0tSWXRobVFwYlBIVXFmckZDVUs0TjB0L29YdjdhY0x1SEVuYW1OZmlrYU5VVTZDClh0TlZFUmZwZTlmU21kRTlzVCtKTDRPNWNpc1RCcWlESGIwaWpOa1lSMHE2cHEwdEpkZGtGNTZ1bGo2WUtOazUKb3EzTVBUeENGQzJCVFRIcmc1N0tMeTdwZjZUL0NjUHk5ZDBSUC81K2NyK1o0NjVTMitEYVBZR3dvQzdKd1RZQgo1L0doelpwc1ovQVN0ZjdwYnJuSVFLVW5pSk1pNjhVZURZWXpyYjhYYjAzeHVNMHE5bXhhS01Hd0VCd2ZKWmZ1CjhZaDFXL1VFYS9Ic3pYNklDSFhqQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ1o4NzNYcHdJaHIKd0dVTGZTYWpqeWdvUXZzOFRPQ2N5YWUwTnl3emw0NEE5VVZsUTVJZVpWVzdyYk1BUDhTMkh4RnJzSmk2VCthNQphSFFsc09jeWZGZ3Q1MHoyRXhvekJIcFY3eHNUb3JMTGx4RUpqMk55RnA1OXIrZXhEVnhPMHUwbTRjR2xiVUVKCndZZEQ5VkFTWTZlZ1QrWXkzaVlMK0NWdmpJQk9wRC8zaDBmOHB2TjJlek02MGE3L0FNWnRyRzNuSXlUZkJZMkcKOG5NdUY1Qk5vTFAzNFVQOUJDeE5LMi8zR2YwNHFyNDk2MnVCbHQ0UjJNR3N4enZGS1JIb2JJRm9XbkpQMWVXbApzQVhzajlUVit1UVFPb2xXdG1xUE5qVGNIc2V2am9EdUpUMjRudzU0TUs0bVg4eXlJbEkyNERvYlhFMEJNK2hoCkhWS0xmT1o0TWYwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
>                 }
>             }
>         }
>     }
> }

### Expected Behavior
The device certificate/key should have been created

### Actual Behavior
The device certificate/key was not created due to error

**Comment by dstokesf5** [comment]
This issue has been confirmed and added to our internal product backlog as AUTOTOOL-1822. Thank you for reporting it.

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.17.0 release.
