### ISSUE TITLE
tmsh modify net interface mgmt media auto

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#166]
### Is your feature request related to a problem? Please describe.
This is not currently available using DO

### Describe the solution you'd like
This to be made available using DO

### Describe alternatives you've considered
N/A

**Comment by jackyatesaustin** [comment]
Editing that this applies to all interfaces, not just mgmt.

**Comment by dstokesf5** [comment]
What use case do you have for this? I believe auto is the default, do you need to set it to something else?
