### ISSUE TITLE
tmsh modify cli global-settings audit enabled

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#168]
### Is your feature request related to a problem? Please describe.
This is not currently available using DO. Currently available - guiAuditLog, tmshAuditLog, and mcpAuditLog

### Describe the solution you'd like
This to be made available using DO

### Describe alternatives you've considered
N/A

**Comment by dstokesf5** [comment]
This setting can be modified using the System.tmshAuditLog property: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/bigip-examples.html#configuring-audit-logging-in-a-declaration
