### ISSUE TITLE
tmsh modify sys db failover.{ie forceactive/forcestandby}

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#170]
### Is your feature request related to a problem? Please describe.
This is not currently available using DO

### Describe the solution you'd like
This to be made available using DO

### Describe alternatives you've considered
N/A

**Comment by dstokesf5** [comment]
Database variables can be configured in DO using the DbVariables class. You can see an example of setting database variables in this example: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/bigip-examples.html#standalone-declaration
