### ISSUE TITLE
tmsh modify sys db setup.run value false 

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#171]
### Is your feature request related to a problem? Please describe.
This is not currently available using DO

### Describe the solution you'd like
This to be made available using DO

### Describe alternatives you've considered
N/A

**Comment by dstokesf5** [comment]
Database variables can be configured in DO using the DbVariables class. You can see an example of setting database variables in this example: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/bigip-examples.html#standalone-declaration

**Comment by dstokesf5** [comment]
Any DB variable can be configured this way. The keys and values of the DbVariables class are passed directly to tmsh with little to no additional mapping.
