### ISSUE TITLE
AOM Configuration

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#172]
### Is your feature request related to a problem? Please describe.
AOM configuration not available in DO

### Describe the solution you'd like
AOM configuration via DO

### Additional context
Moving customer from imperative to declarative onboarding process

**Comment by dstokesf5** [comment]
@jackyatesaustin, can you provide some more context for this request? For example, what is the desired tmsh configuration you are attempting to achieve?

**Comment by jackyatesaustin** [comment]
@dstokesf5 sure, IHAC that is moving from tmsh to DO. They currently configure AOM directly on the console. 

DHCP: N
Hostname: dev.example.com
IP address (required): 1.1.1.1
Network mask (required): 255.255.255.32
Broadcast IP address (optional): 
Default gateway IP address (optional): 1.1.1.10

Do you know if AOM configuration will/can be added to DO?

**Comment by dstokesf5** [comment]
Thank you for your feedback. Unfortunately, it looks like Declarative Onboarding has no way to configure AOM.

Furthermore, this very much looks like a hardware specific feature request which is outside of Declarative Onboarding's scope per the [FAQ](https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/faq.html):
>Does Declarative Onboarding support hardware platforms?
>
>Declarative Onboarding is intended for use with Cloud and Virtual Edition images, but it will also run on and configure hardware platforms. Features specific to hardware platforms, such as creating vCMP guests and setting TurboFlex profiles are not on the Declarative Onboarding roadmap.
