### ISSUE TITLE
modify sys snmp communities delete { <snmp-comm> }

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#175]
### Is your feature request related to a problem? Please describe.
This is not currently available via DO

### Describe the solution you'd like
To be made available via DO

### Describe alternatives you've considered
N/A

**Comment by dstokesf5** [comment]
@jackyatesaustin, can you elaborate on what is missing? If you do not want some snmp communities in your configuration, you should be able to exclude them in your declaration.
