### ISSUE TITLE
DO credentials validation from external provider

### ISSUE THREAD

**Issue by IgnacioLlop** [F5Networks/f5-declarative-onboarding#179]
### Is your feature request related to a problem? Please describe.
On REST calls to DO enpoint at BIG-IP where action need to be done by BIG-IQ, as all license related calls, authentication is controlled by two fields  "bigIqUsername" "bigIqPassword", those are refering to LOCAL authentication on BIG-IQ.

### Describe the solution you'd like

Add field to define external authentication ie "AuthProvider"

### Additional context

On enterprises, authentication is externalized from BIG-IP/IQ, hence having Local Autentication only is a not the best option.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This feature request has been added to our internal product backlog as AUTOTOOL-2058.

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 1.18.0 release.

**Comment by IgnacioLlop** [comment]
I can't find the Postman collection for DO updated to 1.18, can u please upload to to https://github.com/F5Networks/f5-declarative-onboarding/releases thanks.

**Comment by hvaneenoo** [comment]
Thanks @IgnacioLlop for the heads up on the missing collection. It is now posted under release artifacts.
