### ISSUE TITLE
FastL4 profile - reassemble-fragments, syn-cookie-enable, and pva-acceleration

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#182]
### Is your feature request related to a problem? Please describe.
These 3 configuration attributes are not available using DO. Moving from tmsh to DO.

### Describe the solution you'd like
These 3 options to be available via DO

### Describe alternatives you've considered
n/a

**Comment by dstokesf5** [comment]
Fast L4 profiles are a feature of AS3, and are not in the scope of Declarative Onboarding: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/profiles.html#configuring-a-fast-l4-profile-in-a-declaration.

**Comment by jackyatesaustin** [comment]
My apologies
