### ISSUE TITLE
modifying mgmt interface

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#183]
### Is your feature request related to a problem? Please describe.
create sys management-ip <IP-address>
modify net interface mgmt media auto
Commands like these are not available in DO. Ask is that these be added.

### Describe the solution you'd like
For the above commands to be made available in DO

### Describe alternatives you've considered
n/a

**Comment by dstokesf5** [comment]
It looks like changing the media property is a duplicate of #166.

Configuration of the management IP was added in release 1.23.0.
