### ISSUE TITLE
DO reads old dhclient.leases file when it has static ip, causing wrong default gateway

### ISSUE THREAD

**Issue by lasseh** [F5Networks/f5-declarative-onboarding#185]
### Environment
 * Declarative Onboarding Version: v1.16.0
 * BIG-IP Version: BIG-IP v15.1.0.4 (Build 0.0.6) 

### Summary
If the management interface was on a DHCP network and moved to static IP, the dhclient service is restarted under a DO.
This leads to the dhclient not getting a new IP, but reads from the dhclient.leases file and set the old gateway.
This then leads to the f5 going "offline" because of the new/wrong gateway IP.

### Steps To Reproduce
1. Create a new F5 VM with the mgmt interface on a dhcp network
2. Post a DO to the VM
3. Move the mgmt interface to a network without dhcp.
3.1. Set a static IP on mgmt interface
4. Rerun the same DO
5. Observe the following error response:
```
RUNNING
RUNNING
ROLLING_BACK
ERROR:  [tryUntil: max tries reached: dhclient status is * dhclient.service - dhclient automatically configures the management interface when DHCP is available.
   Loaded: loaded (/etc/rc.d/init.d/dhclient; enabled; vendor preset: enabled)
   Active: active (exited) since Mon 2020-10-26 06:48:29 PDT; 1min 2s ago
  Process: 28686 ExecStop=/etc/rc.d/init.d/dhclient stop (code=exited, status=0/SUCCESS)
  Process: 28796 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)

Oct 26 06:48:29 localhost.localdomain systemd[1]: Starting dhclient automatically configures the management interface when DHCP is available....
Oct 26 06:48:29 localhost.localdomain dhclient[28796]: Current management-ip configuration mode for IPV4 is: Static.
Oct 26 06:48:29 localhost.localdomain systemd[1]: Started dhclient automatically configures the management interface when DHCP is available..
```
6. Run "ip r" to check the default gateway is set to the old gateway received from dhcp

### Expected Behavior
DO should not trigger a restart of the dhclient systemd service. Or there should be some checks that the mgmt interface has a static IP.

**Comment by dstokesf5** [comment]
Can you provide a DO declaration that reproduces this issue for you? Also, are you performing step 3.1 with DO or outside of DO?

**Comment by lasseh** [comment]
It does not matter what the DO posted is to reproduce this. As long as the box was on an mgmt network with DHCP, then moved to a network without DHCP, this will happen.

3.1 is done on the console to get it back with the right IP/gateway.

**Comment by dstokesf5** [comment]
There have been a few changes in this area. Are you still seeing this issue with the latest version of Declarative Onboarding?
