### ISSUE TITLE
DO endpoint always respond with JSON

### ISSUE THREAD

**Issue by lasseh** [F5Networks/f5-declarative-onboarding#186]
### Is your feature request related to a problem? Please describe.
When I post a DO it will restart the webserver as part of the configuration. When the webserver is starting it will reply with HTML of the login page on /mgmt/shared/declarative-onboarding. It would be great if it could reply with JSON, so I don't have to code my way around the JSON decode process 

### Describe the solution you'd like
A JSON response with an error message
```json
{
    "code": 403,
    "status": "ERROR",
    "message": "service unavailable",
    "errors": [
        "Webserver is restarting"
    ]
}
```

### Describe alternatives you've considered
A HTTP status of 403

**Comment by dstokesf5** [comment]
Unfortunately, there is no way for Declarative Onboarding to control those HTML error messages. To work around these mixed error messages, we recommend using the webhook feature: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/composing-a-declaration.html#base-components
