### ISSUE TITLE
Invalid config - rolling back after upgrading to 1.17.0

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-declarative-onboarding#190]
### Environment
 * Declarative Onboarding Version: 1.17.0
 * BIG-IP Version: BIG-IP 13.1.1.4 Build 0.0.4 Point Release 4

### Summary
After upgrading DO from 1.15.0 to 1.17.0, I get an invalid config when trying to update the Device Certificate ("one or more properties must be specified"). If I revert back to 1.15.0, it works.

### Steps To Reproduce
1. Submit the following declaration:

Of course, my declaration contains my real certificate and key. For confidentiality reasons, I pasted the declaration found on this page:
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/declarations/auth.html#updating-the-tls-ssl-device-certificate-in-a-declaration

```json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "Common": {
        "class": "Tenant",
        "hostname": "bigip.example.com",
        "deviceCertificate": {
            "class": "DeviceCertificate",
            "certificate": {
                "base64": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCkY1IEZBS0UgQ0VSVElGSUNBVEUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
            },
            "privateKey": {
                "base64": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpGNSBGQUtFIFBSSVZBVEUgS0VZCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t"
            }
        }
    }
}
```

2. Observe the following error response:
```json
{
    "id": "e249a792-0d11-4e63-9219-e474768bcac4",
    "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/e249a792-0d11-4e63-9219-e474768bcac4",
    "result": {
        "class": "Result",
        "code": 202,
        "status": "ROLLING_BACK",
        "message": "invalid config - rolling back",
        "errors": [
            "one or more properties must be specified"
        ]
    },
    "declaration": {}
}
```

### Expected Behavior
The device certificate should be updated with no error. Additionally, the error message should at least specify the name of the missing properties.

### Actual Behavior
Received an "invalid config" error saying that "one or more properties must be specified".

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.21.0 release.
