### ISSUE TITLE
TMOS can revert the device name to bigip1 and DO must respect that

### ISSUE THREAD

**Issue by jgruberf5** [F5Networks/f5-declarative-onboarding#196]
### Environment
 * Declarative Onboarding Version: 1.17.0-3
 * BIG-IP Version: 15.1.2-0.0.9.0

### Summary
While DO is processing a declaration, particularly while adjusting provisioning, other processes in TMOS can revert the device name back to the bigip1 default. Any process which attempts to you provision /tm/cm/device MUST account for device name changes. The device should be resolved by listing the devices and identifying the 'self-device' and resolve the device name from that resource. In this case the configSync IP was being set. The device reverted back to bigip1 and the request to modify localhost /tm/cm/device/~Common~[WRONG DEVICE NAME] fails with 404 until DO retires and times out.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
	"async": true,
	"schemaVersion": "1.0.0",
	"Common": {
		"dnsServers": {
			"nameServers": ["159.8.8.8", "159.8.8.10"],
			"class": "DNS"
		},
		"ntpServers": {
			"timezone": "Europe/Paris",
			"class": "NTP",
			"servers": ["159.8.8.10", "159.8.8.10", "159.8.8.10"]
		},
		"configsync": {
			"configsyncIp": "10.240.129.7",
			"class": "ConfigSync"
		},
		"hostname": "f5-test-prod-n.fr.net.intra",
		"System": {
			"cliInactivityTimeout": 1200,
			"consoleInactivityTimeout": 1200,
			"autoPhonehome": false
		},
		"net_1_2": {
			"interfaces": [{
				"tagged": false,
				"name": "1.2"
			}],
			"tag": 4092,
			"class": "VLAN",
			"mtu": 1500
		},
		"selfip_1_2": {
			"trafficGroup": "traffic-group-local-only",
			"vlan": "net_1_2",
			"allowService": "all",
			"class": "SelfIp",
			"address": "10.240.131.6/24"
		},
		"selfip_1_3": {
			"trafficGroup": "traffic-group-local-only",
			"vlan": "net_1_3",
			"allowService": "all",
			"class": "SelfIp",
			"address": "10.240.128.6/24"
		},
		"selfip_1_1": {
			"trafficGroup": "traffic-group-local-only",
			"vlan": "net_1_1",
			"allowService": "all",
			"class": "SelfIp",
			"address": "10.240.129.7/24"
		},
		"myProvisioning": {
			"afm": "nominal",
			"ltm": "nominal",
			"class": "Provision",
			"asm": "nominal"
		},
		"net_1_3": {
			"interfaces": [{
				"tagged": false,
				"name": "1.3"
			}],
			"tag": 4091,
			"class": "VLAN",
			"mtu": 1500
		},
		"class": "Tenant",
		"net_1_1": {
			"interfaces": [{
				"tagged": false,
				"name": "1.1"
			}],
			"tag": 4093,
			"class": "VLAN",
			"mtu": 1500
		},
		"failoverAddress": {
			"class": "FailoverUnicast",
			"address": "10.240.129.7"
		}
	},
	"class": "Device",
	"label": "generated from DHCPv4 metadata"
}
```

2. Observe the following error response in the restnoded log:
```
Wed, 06 Jan 2021 20:23:54 GMT - fine: [f5-declarative-onboarding: restWorker.js] modify localhost /tm/cm/device/~Common~f5-injected-declarations-03.local {"configsyncIp":"10.240.129.7"}
Wed, 06 Jan 2021 20:23:54 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {"code":404}
```

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by dstokesf5** [comment]
Thank you for reporting this. It has been added to our internal product backlog as AUTOTOOL-2153.

**Comment by dstokesf5** [comment]
Are you still experiencing this issue with the latest release of Declarative Onboarding?

**Comment by jgruberf5** [comment]
I added an assurance that the hostname / device name was set regardless it tmos-cloudinit. I was more worried about bringing it to your attention.
________________________________
