### ISSUE TITLE
Self IP masklen problem

### ISSUE THREAD

**Issue by f5trn** [F5Networks/f5-declarative-onboarding#2]
Configuring the External and Internal Self IP addresses with a /16 masklen seems to fail.  Using /24 works, but does not for F5 GS training lab environment.  Would be very appreciated if you could make it work with /16.  Thanks!

**Comment by seattlevine** [comment]
Can you show us at least the SelfIp section of your declaration and the error message?

**Comment by f5trn** [comment]
Sure.  This works:
`        "internal-self": {
            "class": "SelfIp",
            "address": "172.16.0.31/24",
            "vlan": "internal-vlan",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        },
        "external-self": {
            "class": "SelfIp",
            "address": "10.10.0.31/24",
            "vlan": "external-vlan",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        }`

This fails:
`        "internal-self": {
            "class": "SelfIp",
            "address": "172.16.0.31/16",
            "vlan": "internal-vlan",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        },
        "external-self": {
            "class": "SelfIp",
            "address": "10.10.0.31/16",
            "vlan": "external-vlan",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        }`

With this HTML error message:
`The proxy server could not handle the request <em><a href="/mgmt/shared/declarative-onboarding/">POST&nbsp;/mgmt/shared/declarative-onboarding/</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p>`

Running a GET is more helpful and returns:
`{
  "code": 400,
  "status": "ERROR",
  "message": "bad declaration",
  "errors": [
    {
      "keyword": "format",
      "dataPath": ".Common['internal-self'].address",
      "schemaPath": "network.schema.json#/allOf/1/then/properties/address/format",
      "params": {
        "format": "f5ip"
      },
      "message": "should match format \"f5ip\""
    }
  ],`

The declaration file is filtered through:
`sed -e 's/ \+/ /g' | tr -d '\n'`

And delivered with curl.  Thanks!

**Comment by seattlevine** [comment]
Thanks - there is a bug in our f5ip regex. Will fix in the next release.

**Comment by f5trn** [comment]
Awesome.  Thank you!

**Comment by seattlevine** [comment]
Fixed in 1.2.0-2
