### ISSUE TITLE
Adding management route wipes out dhcp-configured routes

### ISSUE THREAD

**Issue by mikeshimkus** [F5Networks/f5-declarative-onboarding#202]
### Environment
 * Declarative Onboarding Version: 1.16.0
 * BIG-IP Version: 15.1.2

### Summary
In Azure, a multi-NIC VE running 15.1.2 comes up with these 2 routes configured by DHCP:

sys management-route dhclient_route1 {
    description configured-by-dhcp
    gateway 10.0.0.1
    network 168.63.129.16/32
}

sys management-route default {
    description configured-by-dhcp
    gateway 10.0.0.1
    network default
}

Since I am adding a default tmm route out the the external subnet gw 10.0.1.1, I then need to add a management route to the Azure metadata service (requests to metadata can only go out the first NIC, but the tmm route will try to force them out the external interface unless I do):

net route default {
    gw 10.0.1.1
    network default
}   

sys management-route azureMetadata {
    gateway 10.0.0.1
    network 169.254.169.254/32
}

Once I add the default tmm route and azureMetadata management route to my DO declaration, both of the routes configured by dhcp disappear.

I tried adding all 3 routes to my DO config, but then DO complains that default and dhclient_route1 already exist.

What is the expected behavior to add a new management route when dhcp routes already exist? Ideally, wouldn't DO delete and replace any matching routes (with the caveat that you'd need to set dhclient.mgmt to disable)?

### Steps To Reproduce
1. Submit the following declaration:
```json
{
	"schemaVersion": "1.0.0",
	"class": "Device",
	"async": true,
	"label": "example",
	"Common": {
		"class": "Tenant",
		"dbVars": {
			"class": "DbVariables",
			"config.allow.rfc3927": "enable",
			"dhclient.mgmt": "disable"
		},
		"azureMetadata": {
			"class": "ManagementRoute",
			"gw": "10.0.0.1",
			"network": "169.254.169.254/32"
		},
		"default": {
			"class": "Route",
			"gw": "10.0.1.1",
			"network": "default"
		},
		"myDns": {
			"class": "DNS",
			"nameServers": ["8.8.8.8"]
		},
		"myNtp": {
			"class": "NTP",
			"servers": ["0.pool.ntp.org"],
			"timezone": "UTC"
		},
		"mySystem": {
			"autoPhonehome": true,
			"class": "System",
			"hostname": "dd-quick-b0c5e1b7-vm.local"
		},
		"myProvisioning": {
			"class": "Provision",
			"ltm": "nominal",
			"asm": "nominal"
		},
		"external": {
			"class": "VLAN",
			"tag": 4094,
			"mtu": 1500,
			"interfaces": [{
				"name": "1.1",
				"tagged": false
			}]
		},
		"external-self": {
			"class": "SelfIp",
			"address": "10.0.1.4/24",
			"vlan": "external",
			"allowService": "none",
			"trafficGroup": "traffic-group-local-only"
		},
		"internal": {
			"class": "VLAN",
			"tag": 4093,
			"mtu": 1500,
			"interfaces": [{
				"name": "1.2",
				"tagged": false
			}]
		},
		"internal-self": {
			"class": "SelfIp",
			"address": "10.0.2.4/24",
			"vlan": "internal",
			"allowService": "default",
			"trafficGroup": "traffic-group-local-only"
		}
	}
}
```

### Expected Behavior
DO either adds my new route to the existing management routes, or succeeds with a declaration that includes all the routes.

### Actual Behavior
Lose connectivity to the mgmt interface in the middle of DO task.  Log in via serial console and notice that tmsh list sys management-route only returns the azureMetadata route, and the routes configured by dhcp are missing. REST logs show dhcp routes deleted:

Tue, 26 Jan 2021 00:52:16 GMT - fine: [f5-declarative-onboarding: restWorker.js] delete localhost /tm/sys/management-route/~Common~default null

Tue, 26 Jan 2021 00:52:16 GMT - fine: [f5-declarative-onboarding: restWorker.js] delete localhost /tm/sys/management-route/~Common~dhclient_route1 null

**Comment by dstokesf5** [comment]
Thank you for reporting this. I have added it to our internal product backlog as AUTOTOOL-2225.

**Comment by mikeshimkus** [comment]
The following DO config gives me what I want.  Closing this issue.

            "azureMetadata": {
              "class": "ManagementRoute",
              "gw": "10.0.0.1",
              "network": "169.254.169.254/32"
            },
            "dhclient_route1": {
              "class": "ManagementRoute",
              "gw": "10.0.0.1",
              "network": "168.63.129.16/32"
            },
            "default": {
              "class": "ManagementRoute",
              "gw": "10.0.0.1",
              "network": "default"
            },
            "defaultRoute": {
              "class": "Route",
              "gw": "10.0.1.1",
              "network": "default"
            }
