### ISSUE TITLE
Self-IP firewall Policy support

### ISSUE THREAD

**Issue by stanislaspiron** [F5Networks/f5-declarative-onboarding#203]
### Is your feature request related to a problem? Please describe.
To enable network security firewall on BIG-IP, we can configure all these steps with automation toolchain:
- Provision AFM with DO
- set Default Firewall Options >> Virtual Server & Self IP Contexts to Drop with DO (dbvar tm.fw.defaultaction)
- create Network Firewall policies assigned to VS  with AS3

But if we set configure default drop policy, required traffic like GTM iQuery and cluster synchronization will be dropped.

### Describe the solution you'd like

- Create new Class Firewall_Policy (same name as AS3 Firewall Policy Class) to create local network firewall policies
- add following parameters in SelfIp class:

```
enforcedFirewallPolicy
stagedFirewallPolicy
```

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request as AUTOTOOL-2232 in our internal product backlog.

**Comment by dstokesf5** [comment]
This issue was resolved in the 1.20.0 release.
