### ISSUE TITLE
DoS Protection at Device level

### ISSUE THREAD

**Issue by nergalex** [F5Networks/f5-declarative-onboarding#205]
### Is your feature request related to a problem? Please describe.
Need to automate auto-scaling of a scrubbing center based on DHD VEs, but DoS Protection configuration at Device level does not exist in DO

### Describe the solution you'd like
A new class to configure DoS Protection configuration at Device level, same as in UI : Configure Security >> DoS Protection >> Device Protection

**Comment by dstokesf5** [comment]
Can you provide an example of the tmsh configuration you are trying to achieve?
