### ISSUE TITLE
DO declaration with multiple modules requires manual reboot and re-post

### ISSUE THREAD

**Issue by vbojko** [F5Networks/f5-declarative-onboarding#21]
when I declare:
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json",
    "schemaVersion": "1.3.0",
    "class": "Device",
    "async": true,
    "label": "Basic onboarding",
    "Common": {
        "class": "Tenant",
        "myLicense": {
            "class": "License",
            "licenseType": "regKey",
            "regKey": "some license"
        },
        "myDns": {
            "class": "DNS",
            "nameServers": [
                "10.140.0.2"
            ],
            "search": [
                "us-west-1.compute.internal"
            ]
        },
        "myNtp": {
            "class": "NTP",
            "servers": [
                "0.pool.ntp.org",
                "1.pool.ntp.org",
                "2.pool.ntp.org"
            ],
            "timezone": "UTC"
        },
        "admin": {
            "class": "User",
            "userType": "regular",
            "password": "2somepwd123",
            "shell": "bash"
        },
        "myProvisioning": {
            "class": "Provision",
            "ltm": "nominal",
            "gtm": "minimum",
            "apm": "nominal",
            "asm": "nominal",
            "avr": "nominal"
        },
        "internal": {
            "class": "VLAN",
            "tag": 4093,
            "interfaces": [
                {
                    "name": "1.2",
                    "tagged": true
                }
            ]
        },
        "internal-self": {
            "class": "SelfIp",
            "address": "10.140.2.100/24",
            "vlan": "internal",
            "allowService": "none",
            "trafficGroup": "traffic-group-local-only"
        },
        "external": {
            "class": "VLAN",
            "tag": 4094,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ]
        },
        "external-self": {
            "class": "SelfIp",
            "address": "10.140.1.100/24",
            "vlan": "external",
            "allowService": "none",
            "trafficGroup": "traffic-group-local-only"
        },
        "default": {
            "class": "Route",
            "gw": "10.140.1.1",
            "network": "default",
            "mtu": 1500
        }
    }
}

I have to manually reboot big-ip.
after reboot not all modules are provisioned. To got the final declared state I have to re-POST DO config.

**Comment by seattlevine** [comment]
Resolved in 1.3.1
