### ISSUE TITLE
Management Interface Security Policy

### ISSUE THREAD

**Issue by tizianorosato-gr** [F5Networks/f5-declarative-onboarding#218]
### Is your feature request related to a problem? Please describe.
Management Interface Security Policy 
from the GUI: System\Platform\Security: Management Port

### Describe the solution you'd like
the ability to create and then manage the policy and rules in full.

### Describe alternatives you've considered
At the moment I can configure the same using tmsh commands.

### Additional context
This should be done using LTM only, no AFM at all.

**Comment by megamattzilla** [comment]
I have customers running into this issue as well.  

Trying to configure MGMT port firewall rules per KB: https://support.f5.com/csp/article/K46122561 does not seem to be currently supported in DO schema. We would love to see the option to configure MGMT firewall rules in DO schema.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this request to our internal product backlog as     AUTOTOOL-2676.

**Comment by thilan3547** [comment]
Do we have any timelines for this feature to be available? After doing the initial configurations via DO I had to do the management interface security policy manually and it would be time-saving and make the device provisioning via DO complete if this feature is available.

**Comment by malith100** [comment]
There is no option available to configure - "security firewall management-ip-rules { }" via declarative-onboarding.
Can I know the timelines on that?

**Comment by dstokesf5** [comment]
Development has been completed on this feature and it will be available in the 1.24.0 release.

**Comment by dstokesf5** [comment]
This was resolved with the 1.24.0 release of Declarative Onboarding.

**Comment by rukshanpk** [comment]
Hello @dstokesf5... my f5 is in the version '15.1.2.1'. But I cannot add mgmt firewall rules without provisioning AFM module, which should not be the case. My schemaVersion is "1.24.0". Could you kindly assist me with this ?

**Comment by dstokesf5** [comment]
@rukshanpk Please create a new bug to address the issue you are experiencing. It sounds like there was an incorrect assumption about required modules for mgmt firewall rules.

**Comment by rukshanpk** [comment]
@dstokesf5  thank you very much for your reply. I have raise a bug report for this #279
