### ISSUE TITLE
Auto Last hop per vlan

### ISSUE THREAD

**Issue by nitzan-tz** [F5Networks/f5-declarative-onboarding#220]
### Is your feature request related to a problem? Please describe.
We need to have the ability to disable auto last hop per vlan 

### Describe the solution you'd like
To have this option per vlan like you have for Tunnel interface

### Describe alternatives you've considered
The only alternative I see it to do it manually or disable globally with sys db 

### Additional context
This is the command I would like to have on tmsh
modify net vlan INTERNAL auto-lasthop disabled

**Comment by dstokesf5** [comment]
Thank you for your feedback. This issue has been added to our internal product backlog as  AUTOTOOL-2509.

**Comment by dstokesf5** [comment]
This issue has been resolved by the 1.22.0 release.
