### ISSUE TITLE
Regression: TMOS v15.1.x LDAP referrals settings not reflected by DO

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-declarative-onboarding#221]
### Environment
Current environnement:
 * Declarative Onboarding Version: 1.20
 * BIG-IP Version: 14.1.2

Ongoing migration to:
 * Declarative Onboarding Version: 1.20
 * BIG-IP Version: 15.1.2

### Summary

Prior TMOS version 15.1.0 , setting “LDAP referrals” was done using "dbvars" class in DO.

Typical DO declaration: 

"dbvars": {
            "class": "DbVariables",
            "ui.advisory.enabled": true,
            "ui.advisory.color": "green",
            **"systemauth.referrals": "no"**
        }

Since TMOS version 15.1.0 , “LDAP referrals” settings have been deprecated with dbvars and "systemauth.referrals": "no" has no effect. 

LDAP referrals sysdb deprecation is documented here : https://support.f5.com/csp/article/K17311

### Steps To Reproduce
1. Submit the following declaration on v15.1.2

"dbvars": {
            "class": "DbVariables",
            "ui.advisory.enabled": true,
            "ui.advisory.color": "green",
            "systemauth.referrals": "no"
        }

### Expected Behavior

Expected behavior is to abstract and take into account this TMOS change with LDAP Referral settings.

As a declarative Interface, DO declaration needs to be valid whatever TMOS version is.

An acceptable fix would be to have **"systemauth.referrals": "no"** abstracted and still valid (eventhough it's not a dbvar behind the scene)

if not, an acceptable fix would to have a new class/function that handle LDAP referral setting.

### Actual Behavior
DO declaration with LDAP referral set to no has not effect on TMOS 15.1.0 and up.

This TMOS behavior change is breaking DO deployements and is preventing customer from upgrading hundred (100) of VEs.

**Comment by dstokesf5** [comment]
I am changing this from a bug to a feature request to expose the new referrals setting as a new property for ldap in DO's Authentication class.

**Comment by dstokesf5** [comment]
I have added this request to our internal product backlog as AUTOTOOL-2433.

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.21.0 release.
