### ISSUE TITLE
Support a VE image that has rpm's already loaded

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-declarative-onboarding#223]
### Is your feature request related to a problem? Please describe.
When using the F5 image generator, you can build an image of BIG-IP that already has the rpm files located in /var/config/rest/downloads.  In which case, the required section of DO, icontrollx_package_urls: , isn't necessary

I'm asking that there be a new option introduced that assumes the rpm files are in a directory and will just be installed and used by DO instead of requiring a URL for them.

**Comment by dstokesf5** [comment]
The `icontrollx_package_urls` property you mentioned is not a property that is part of Declarative Onboarding. I believe that is part of TMOS declared: https://clouddocs.f5.com/cloud/public/v1/shared/cloudinit.html#cloudconfig-tmosdecl. Please file a ticket with F5 support for help with that product.

**Comment by thomsonjames** [comment]
Ah, yes, you are very correct, thanks
