### ISSUE TITLE
Race condition when creating self-ip on non-default route-domain

### ISSUE THREAD

**Issue by enceladus-beep** [F5Networks/f5-declarative-onboarding#234]
### Environment
 * Declarative Onboarding Version: 1.20
 * BIG-IP Version: 15.1.2.1

### Summary
The declaration tries to create:
- 3 Trunks 
- 3 Vlans 
- 2 Route domains 
- 2 Self-IP on non-def route-domain 

The self-ip creation fails with:

`01070712:3: Cannot get device index for <vlan> in rd<route domain number> - ioctl failed: No such device`

### Internal bug 
This is an external bug created to include the fix in the release note. 
This bug has been added to our internal product backlog as AUTOTOOL-2497.

**Comment by dstokesf5** [comment]
Why was this GitHub issue created? We do not need a GitHub issue to include a bug fix in the Declarative Onboarding release notes.

**Comment by enceladus-beep** [comment]
> 
> 
> Why was this GitHub issue created? We do not need a GitHub issue to include a bug fix in the Declarative Onboarding release notes.

I wanted to include the error string to make it easier for other users to find the bug, and the version where the fix will be included.

**Comment by dstokesf5** [comment]
Sounds reasonable to me. Thanks.

**Comment by dstokesf5** [comment]
This issue has been resolved by the 1.22.0 release.
