### ISSUE TITLE
GCP 3nic management swap, DO license with eth0 (external) MAC address

### ISSUE THREAD

**Issue by jfreeland** [F5Networks/f5-declarative-onboarding#242]
### Environment
 * Declarative Onboarding Version: `v1.19.0`
 * BIG-IP Version: `15.1.2`

### Summary
When running a 3nic F5 instance in Google Cloud Platform (GCP) you have to swap our external interface (typically `eth1`) and our management interface (typically `eth0`).  GCP can only send traffic from a load balancer to `eth0` and thus this swap is required to support ingress traffic.  An example of how this can be done: https://github.com/memes/terraform-google-f5-bigip/blob/main/modules/metadata/files/multiNicMgmtSwap.sh

When using Declarative Onboarding to acquire a license from BigIQ, DO always selects the MAC address for `eth0` despite `eth0` not being the management interface.

DO does still use the IP address of the management interface when acquiring the license.

This produces inconsistent results when auditing and tracking licenses.

### Steps To Reproduce
1. Submit the following declaration:
...

2. Observe the following error response:
...

### Expected Behavior
The MAC address and IP address of the management interface should be used when acquiring a license from BigIQ.

### Actual Behavior
The MAC address of the external interface and the IP address of the management interface are used to acquire a license from BigIQ.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This issue has been added to our internal product backlog as AUTOTOOL-2532.

**Comment by dstokesf5** [comment]
This issue has been resolved by the 1.22.0 release.
