### ISSUE TITLE
LTM Sometimes Binds Wrong IP Address When Multiple IP's Are Declared in DO

### ISSUE THREAD

**Issue by Tylerbrown7213** [F5Networks/f5-declarative-onboarding#243]
Environment
 * Declarative Onboarding Version: 1.16.0
 * BIG-IP Version: 15.1.2.1

Summary
I'm working on a Google Cloud Platform (GCP) deployment which uses SNAT Auto Map on Virtual Servers, and requires multiple Self IP's on the Internal Vlan to avoid source port exhaustion issues.  When using DO to do the initial configuration, I sometimes see the LTM binds the incorrect IP address to the Internal Interface.

```
ifconfig
internal: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
        inet 10.77.3.37  netmask 255.255.255.255  broadcast **10.77.3.37**
        inet6 fe80::4001:aff:fe4d:31a  prefixlen 64  scopeid 0x20<link>
        ether 42:01:0a:4d:03:1a  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 180 (180.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
tmsh list net self
net self internal-localself {
    address **10.77.3.26/32**
    allow-service {
        default
    }
    traffic-group traffic-group-local-only
    vlan internal
}
```

In the example above, the tmsh list self show's the same IP address as the GCP console for nic2.  The Ip shown in the ifconfig is one of the additional self IP used for SNAT, but should not be binded to the internal interface. 

1. Submit the following declaration:
```
"internal-localself": {
            "class": "SelfIp",
            "address": "${local_selfip_int}/32",
            "vlan": "internal",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        },
%{ for k,v in snat_ips ~}
        "${k}": {
            "class": "SelfIp",
            "address": "${v}/32",
            "vlan": "internal",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        },
%{ endfor ~}        
```
2. Observe the following error response:
.....

Expected Behavior
In the above declaration, I would expect that the "internal-localself" IP address would be binded to the internal nic.

Actual Behavior
In 7 out of 10 test deployments, I observed at least one of the LTM's in a cluster didn't have the correct IP address binded to the internal nic.

**Comment by dstokesf5** [comment]
Can you please provide the VLAN part of your DO declaration?

**Comment by Tylerbrown7213** [comment]
@dstokesf5 Below is a snip of the VLAN portion of the DO declaration.

 },
         "internal": {
            "class": "VLAN",
            "tag": 4093,
            "mtu": 1460,
            "interfaces": [
                {
                    "name": "1.2",
                    "tagged": false
                }
            ]
        },
       "external": {
            "class": "VLAN",
            "tag": 4092,
            "mtu": 1460,
            "interfaces": [
                {
                    "name": "1.0",
                    "tagged": false
                }
            ]
        },
