### ISSUE TITLE
Support Encrypted passwords for `user` class

### ISSUE THREAD

**Issue by trinaths** [F5Networks/f5-declarative-onboarding#245]
### Is your feature request related to a problem? Please describe.

`user` class presently doesn't support encrypted passwords. Only clear text data is being accepted. 

### Describe the solution you'd like

Please support encrypted password for `user` class. Like its supported in tmsh.

`$ tmsh modify /auth user admin encrypted-password '${encrypted_password}'`

### Describe alternatives you've considered

None.

### Additional context
https://github.com/f5devcentral/terraform-aws-bigip-module/issues/40

**Comment by dstokesf5** [comment]
Closing as a duplicate of #194.
