### ISSUE TITLE
RFE: ASM advanced settings variables

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-declarative-onboarding#251]
### Is your feature request related to a problem? Please describe.
Changing any ASM Advanced settings variable requires a restart of the ASM service, to be effective. The DO phase would be
the perfect phase in the deployment to apply effectively such configuration change. 

### Describe the solution you'd like
The possibility to configure ASM advanced settings variables in the DO declaration. If any variable is configured, DO takes care of applying the change(s) after the ASM has been provisioned, and restart the asm service.
Goal is: after the DO has finished, the variables are set and are effective (due to the asm service restart).

### Additional context
Those ASM advanced settings variables can only be configured once ASM has been provisioned. Additionally, there are two limitations:
- there is no way, programmatically, to figure out if there is a pending asm restart required (after changing those variables)
- there is no way to set the asm service to automatically restart, if any variable change has been made

Therefore, DO is the best phase in the deployment to set those variables and get them effective.

**Comment by dstokesf5** [comment]
Can you provide some example tmsh configuration of the settings you would like to change?

**Comment by amolari** [comment]
@dstokesf5 Those are not set by a TMSH command, but on the CLI (can be set through UI too) with a Perl script:
```
#  /usr/share/ts/bin/add_del_internal
USAGE:
/usr/share/ts/bin/add_del_internal add <param_name> <param_value> [--default <default_value>]
/usr/share/ts/bin/add_del_internal update <param_name> <param_value> [--default <default_value>]
/usr/share/ts/bin/add_del_internal delete <param_name>
```

AFAIK there is no central documentation for those (and some are not publicly documented but are provided by F5 support), but one can find information for specific variables on different KBs:
https://support.f5.com/csp/article/K13787#SecureCLI
https://support.f5.com/csp/article/K11434152#p2
[...]
In the declaration we could set a map of the variables such as
```
{ 
  "<param_name1>": "<param_value1>",
  "<param_name2>": "<param_value2>",  
  "<param_name3>": "<param_value3>"
}
```

Those would be applied (after the ASM provisioning) such as the following commands:
```
/usr/share/ts/bin/add_del_internal add <param_name1> <param_value1>
/usr/share/ts/bin/add_del_internal add <param_name2> <param_value2>
/usr/share/ts/bin/add_del_internal add <param_name3> <param_value3>
```

And right after that the ASM module would be restarted (mandatory for most but not all of those system variables to take effect) such as:
`tmsh restart sys service asm`

**Comment by dstokesf5** [comment]
Thank you for the additional information. I am reviewing it now.
