### ISSUE TITLE
Unable to use remote user on BIG-IQ to deploy DO declaration

### ISSUE THREAD

**Issue by IkueMoto** [F5Networks/f5-declarative-onboarding#259]
When connecting to BIG-IQ using a local admin user it works as expected, however when connecting to the BIG-IQ using a different provider I see the follow error logged in /var/log/restnoded/restnoded.log:

Fri, 10 Sep 2021 15:42:16 GMT - finest: [f5-declarative-onboarding: restWorker.js] Got onboarding request.
Fri, 10 Sep 2021 15:42:16 GMT - fine: [f5-declarative-onboarding: restWorker.js] Onboard starting for task b4da7461-6588-43da-a3a5-3d3b4d125255
Fri, 10 Sep 2021 15:42:16 GMT - info: [f5-declarative-onboarding: doUtil.js] Platform: BIG-IQ
Fri, 10 Sep 2021 15:42:16 GMT - finest: [f5-declarative-onboarding: restWorker.js] done w/ initial account setup
Fri, 10 Sep 2021 15:42:16 GMT - finest: [f5-declarative-onboarding: restWorker.js] Passing to TCW
Fri, 10 Sep 2021 15:42:16 GMT - info: [f5-declarative-onboarding: restWorker.js] TCW task failed: [RestOperationNetWorkerHandler]: bad response received: 400 - Get document for key: shared/authz/users/remoteuser returned nothing
Fri, 10 Sep 2021 15:42:16 GMT - severe: [f5-declarative-onboarding: configManager.js] Error getting current config: Cannot read property 'list' of undefined

Remote user is indeed missing from shared/authz/users/ however it's defined in the BIG-IQ GUI: System Tab -> USER MANAGEMENT -> Users (not local)

AS3 declarations work fine with remote users, why not with DO? 
Not working in BIG-IQ v7.1.0 (DO 1.16), nor BIG-IQ v8.1.0.1 (DO 1.23)

**Comment by IkueMoto** [comment]
Example declaration pushed to BIG-IQ with remote logon Provider:

{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/latest/remote.schema.json",
    "class": "DO",
    "declaration": {
        "schemaVersion": "1.11.0",
        "class": "Device",
        "async": true,
        "Common": {
            "class": "Tenant",
            "myDbVariables": {
                "class": "DbVariables",
                "ui.advisory.enabled": "true",
                "ui.advisory.color": "red",
                "ui.advisory.text": "Configuration deployed with AS3. Do not make any change directly on the BIG-IP or those changes may be lost."
            }
        }
    },
    "targetUsername": "admin",
    "targetHost": "<BIG-IP_targetHost>",
    "targetPassphrase": "admin",
    "bigIqSettings": {
      "failImportOnConflict": false,
      "conflictPolicy": "USE_BIGIQ",
      "deviceConflictPolicy": "USE_BIGIP",
      "versionedConflictPolicy": "KEEP_VERSION"
    }
}

**Comment by dstokesf5** [comment]
Please resubmit this issue following one of the provided issue templates. That will help us better process and track your issue.

**Comment by IkueMoto** [comment]
Where can I find the issue template please?

**Comment by dstokesf5** [comment]
https://github.com/F5Networks/f5-declarative-onboarding/issues/new/choose
