### ISSUE TITLE
Issue in creating new routes/route domains with Declarative Onboarding

### ISSUE THREAD

**Issue by chrismackinnon** [F5Networks/f5-declarative-onboarding#266]
So a snippet of my declaration currently looks like:

**"GW-VLAN81":{ 
          "class":"Route",
          "gw": "128.233.210.1%2",
          "network": "0.0.0.0%2/0"
      },**

And I get the following error:

**{ 
        "id": "2db4286e-6c95-4d60-8c2d-0bff7908e1a8",
        "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/2db4286e-6c95-4d60-8c2d-0bff7908e1a8",
        "code": 422,
        "status": "ERROR",
        "message": "invalid config - rolled back",
        "errors": [
            "transaction failed:01070712:3: Cannot create static route: 0.0.0.0%2/0 gw 128.233.210.1%2 on interface  in rd2 - netlink error: 101 (Network is unreachable)",
            "transaction failed:01070712:3: Cannot create static route: 0.0.0.0%2/0 gw 128.233.210.1%2 on interface  in rd2 - netlink error: 101 (Network is unreachable)"
        ],
        "result": {
            "class": "Result",
            "code": 422,
            "status": "ERROR",
            "dryRun": false,
            "message": "invalid config - rolled back",
            "errors": [
                "transaction failed:01070712:3: Cannot create static route: 0.0.0.0%2/0 gw 128.233.210.1%2 on interface  in rd2 - netlink error: 101 (Network is unreachable)",
                "transaction failed:01070712:3: Cannot create static route: 0.0.0.0%2/0 gw 128.233.210.1%2 on interface  in rd2 - netlink error: 101 (Network is unreachable)"
            ]
        },**

Able to run the following command successfully within tmsh:
 
**vlanID=81           # VLAN ID 
rdID=2               # Route Domain ID
rdGWIP=128.233.210.1   # Route Domain Gateway IP** 

#ACTIVE: Create a gateway with route domain on active unit only

**tmsh create net route GW-VLAN$vlanID \
     description "Route domain gateway for VLAN$vlanID" \
     network default%$rdID \
     gw $rdGWIP%$rdID**

Any information/guidance would be much appreciated.

Thanks,
-Chris Mac.

**Comment by chrismackinnon** [comment]
Referencing F5 Support Case #C3663598

**Comment by dstokesf5** [comment]
After variable substitution, it looks like your tmsh command is effectively:
```
tmsh create net route GW-VLAN81 network default%2 gw 128.233.210.1%2
```

However, the DO snippet you provided would be equivalent to:
```
tmsh create net route GW-VLAN81 network 0.0.0.0%2/0 gw 128.233.210.1%2
```
Does this second command work for you on tmsh?
