### ISSUE TITLE
Adding Management Route Resets Management IP to default

### ISSUE THREAD

**Issue by markjackman** [F5Networks/f5-declarative-onboarding#269]
Environment
Declarative Onboarding Version: v1.24.0
BIG-IP Version: 15.1.3.1

Summary
When deploying a validated DO declaration with management routes, my VE reverts to the default 192.168.1.245 address. Without the management route, the declaration completes and the static management IP stays, no issues.

Prior to the declaration push my VE:
sys management-ip 10.168.52.150/24 {
    description configured-statically
}

sys global-settings {
    gui-setup disabled
    mgmt-dhcp disabled
}

### Steps To Reproduce
Add Management Route class to working declaration e.g.
 
        "mgmt1": {
            "class": "ManagementRoute",
            "gw": "10.168.52.1",
            "network": "10.10.10.0/24"
        },

2. Observe the following error response:
The declaration appears to completes however the management IP is reset to default

sys management-ip 192.168.1.245/24 {
    description static-fallback
}

sys global-settings {
    gui-setup disabled
    hostname bigip.example.com
}

### Expected Behavior
Pushing a declaration with the management route class should not reset the management IP to defaults

### Actual Behavior
The declaration appears to completes however the management IP is reset to default

**Comment by walterk82** [comment]
Do you still have the mgmt ip as part of the declaration?  Can you post the _full_ device declaration?

**Comment by markjackman** [comment]
Hi wlaterk82,

I attempt to deploy with the management IP class below in the declaration, however I encounter an issue with “The requested management IP (10.168.52.151) already exists”

        "myManagementIp": {
            "class": "ManagementIp",
            "address": "10.168.52.151/24",
            "remark": "this is my management ip"
        },

Here is the declaration :

{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/latest/base.schema.json",
    "schemaVersion": "1.24.0",
    "class": "Device",
    "async": true,
    "label": "Clustered BIG-IP declaration for declarative onboarding",
    "Common": {
        "class": "Tenant",
        "hostname": "bigip.example.com",
        "mgmt1": {
            "class": "ManagementRoute",
            "gw": "10.168.52.1",
            "network": "10.10.10.0/24"
        }
    }
}

**Comment by difanzhao** [comment]
I experience the same problem... Setting the mgmt route will remove the MGMt interface config. I am running on 14.1.4.4 with the DO version 1.24.0

**Comment by dstokesf5** [comment]
Thank you for your feedback. This issue has been added to our internal product backlog as AUTOTOOL-2805.

**Comment by dstokesf5** [comment]
This has been resolved in the 1.26.0 release.
