### ISSUE TITLE
Provide ability to configure remote high speed log destinations

### ISSUE THREAD

**Issue by njculver** [F5Networks/f5-declarative-onboarding#284]
### Is your feature request related to a problem? Please describe.
No classes exist to allow for the configuration of remote high speed log destinations.

### Describe the solution you'd like
The ability to configure high speed log destinations similarly to syslog remote servers.

### Describe alternatives you've considered
Adding tmsh commands to startup script.

### Additional context
#12 mentioned these tmsh commands which look relevant
```
tmsh create sys log-config destination remote-high-speed-log name distribution adaptive pool-name <poolHSL> protocol tcp
tmsh create sys log-config publisher <name> destinations add { <destination> }
```

**Comment by dstokesf5** [comment]
AS3 allows you to configure log [destinations](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schemaref/Log_Destination.schema.json.html) and [publishers](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schemaref/Log_Publisher.schema.json.html). Here is an example: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#using-splunk-as-a-log-destination.

Is there anything missing from these classes for your use case?

**Comment by njculver** [comment]
As a F5 novice, I didn't think to check AS3. It seems like that should work so I'll give that a try.
