### ISSUE TITLE
base.schema.json has the wrong url

### ISSUE THREAD

**Issue by anderpups** [F5Networks/f5-declarative-onboarding#285]
### Environment
 * Declarative Onboarding Version: latest
 * BIG-IP Version: latest

### Summary
The url on the base.schema.json is wrong and throws a 404. 
I believe it should be: https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/latest/base.schema.json

**Comment by dstokesf5** [comment]
Thank you for your feedback and PR. I have added this issue to our internal product backlog as AUTOTOOL-2941.

**Comment by dstokesf5** [comment]
This has been resolved in the 1.28.0 release.
