### ISSUE TITLE
TMOS 14.1 and root password

### ISSUE THREAD

**Issue by nergalex** [F5Networks/f5-declarative-onboarding#29]
Hi,
When an onboarding config includes achange of root password, I cannot retrieve the old password on a TMOS v14.1, even if I use the admin password as described in the [documentation](https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/composing-a-declaration.html#id5).
Which old password do I have to set in v14.1+ ?

### JSON body request
{
    "async": false,
    "schemaVersion": "1.3.0",
    "Common": {
        "root": {
            "userType": "root",
            "newPassword": "NewTest4Issue!",
            "oldPassword": "Test4Issue!",
            "class": "User"
        },
        "dbvars": {
            "systemauth.disablerootlogin": false,
            "ui.advisory.enabled": true,
            "ui.advisory.text": "POC_Public_cloud",
            "class": "DbVariables",
            "ui.advisory.color": "green"
        },
        "class": "Tenant",
        "route_internal": {
            "gw": "10.0.2.1",
            "mtu": 1500,
            "class": "Route",
            "network": "10.0.0.0/8"
        }
    },
    "class": "Device",
    "label": "declarative_onboarding_for_ADC_in_HUB"
}

### answer
{
    "code": 422,
    "status": "ERROR",
    "message": "invalid config - rolled back",
    "errors": [
        "Old password is incorrect."
    ],
    "declaration": {
        "async": false,
        "schemaVersion": "1.3.0",
        "Common": {
            "root": {
                "userType": "root",
                "class": "User"
            },
            "dbvars": {
                "systemauth.disablerootlogin": false,
                "ui.advisory.enabled": true,
                "ui.advisory.text": "POC_Public_cloud",
                "class": "DbVariables",
                "ui.advisory.color": "green"
            },
            "class": "Tenant",
            "route_internal": {
                "gw": "10.0.2.1",
                "mtu": 1500,
                "class": "Route",
                "network": "10.0.0.0/8"
            }
        },
        "class": "Device",
        "label": "declarative_onboarding_for_ADC_in_HUB"
    }
}

**Comment by focrensh** [comment]
The old password would be the one you setup right before you installed DO.

**Comment by nergalex** [comment]
OK thank you
By default, root access is not activated, so I understand that the root password cannot be set initially with DO, am I correct ?

**Comment by focrensh** [comment]
That is correct. Admin account must be setup prior to first DO declaration.

**Comment by nergalex** [comment]
Thanks

**Comment by difanzhao** [comment]
Hi @focrensh , do you mean that we need to manually activate the root account first (with an initial password) before we can use the DO to change its password? 
I deployed a pair of F5 in Azure and the admin account has been created by the Azure ARM template. The admin account works fine for both WebGUI or SSH.
