### ISSUE TITLE
documentation issue under:  Installing Declarative Onboarding using cURL from the Linux shell

### ISSUE THREAD

**Issue by caliraftdude** [F5Networks/f5-declarative-onboarding#291]
Working with the clouddocs presentation of this documentation here:
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/installation.html

Specifically under,  Installing Declarative Onboarding using cURL from the Linux shell:

```
DATA="{\"operation\":\"INSTALL\",\"packageFilePath\":\"/var/config/rest/downloads/$FN\"}"

curl -kvu $CREDS "https://$IP/mgmt/shared/iapp/package-management-tasks" -H "Origin: https://$IP" -H 'Content-Type: application/json;charset=UTF-8' --data $DATA

```
This call from curl (or any other client) should be of type POST, otherwise you will only get a query which doesn't appear to perform the installation.

**Comment by dstokesf5** [comment]
cURL assumes POST for the method when the `--data` flag is being used.

If you still have an issue, please open a new ticket and be sure to fill out one of the provided templates. Using the templates will help us track your issue and provide better assistance.
