### ISSUE TITLE
Schema Validation (deployment works)- Does not appear to validate Class: SnmpTrpDestination - "Destination" properly

### ISSUE THREAD

**Issue by samualblair** [F5Networks/f5-declarative-onboarding#293]
* Declarative Onboarding Version: 1.27.0
 * BIG-IP Version: N/A

### Summary
The Schema Validation - Does not appear to validate Class: SnmpTrpDestination - "Destination" properly.
When using schema reference in Visual studio code I am seeing warnings when using any value, but IPv4 address works fine when DO is pushed.

In addition on CloudDocs there is no 'Value' shown, just a blank box, possible due to mistake in Schema?
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/schema-reference.html#snmptrapdestination

### Steps To Reproduce
1. Prepare a declaration, verify against schema:
```json
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/v1.27.0/src/schema/latest/base.schema.json",
    "schemaVersion": "1.6.0",
    "class": "Device",
    "Common": {
    	"class": "Tenant",
    	"hostname": "example.local",
        "SNMPV3_SETTINGS": {
            "class": "SnmpTrapDestination",
            "version": "3",
            "destination": "10.0.0.1",
            "port": 161,
            "network": "management",
            "engineId": "snmpEngineID_v3_HERE",
            "securityName": "snmp_v3_username_1",
            "authentication": {
                "protocol": "sha",
                "password": "snmp_v3_auth_password"
            },
            "privacy": {
                "protocol": "aes",
                "password": "snmp_v3_priv_password"
            }
        },
    }
}
```

2. Observe the following warning (in Visual Studio Code, no warning observed during deployment):
```
        "NMPV3_SETTINGS": {
            "class": "SnmpTrapDestination",
            "destination": "10.0.0.1", <--- WARNING HERE , just marked as invalid with comment "Specifies the address for trap destination"
        },
```

### Expected Behavior
I would expect Schema to not show warning when a valid entry is present.

I would expect cloud docs to specify what is or isn't valid.

I would expect DO declaration to work.

### Actual Behavior

When using schema reference in Visual studio code I am seeing warnings when I use something like
        "SNMPV3_SETTINGS": {
            "class": "SnmpTrapDestination",
            "destination": "10.0.0.1",
        },

Example: 
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/v1.27.0/src/schema/latest/base.schema.json",

or

    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/latest/base.schema.json",

There is a warning shown, when a valid entry is present.

Cloud docs to specify what is or isn't valid.

DO declaration does still work.

**Comment by dstokesf5** [comment]
This looks like a problem in VS Code. Here is the relevant schema:
```json
                    "destination": {
                        "description": "Specifies the address for the trap destination.",
                        "type": "string",
                        "oneOf": [
                            { "format": "ipv4" },
                            { "format": "ipv6" }
                        ]
                    },
```

VS Code says that `"10.0.0.1"` is matching both the `ipv4` and `ipv6` formats, when it should only be matching the `ipv4` format. As far as I can tell the DO schema is valid here and is not doing anything strange.

**Comment by samualblair** [comment]
Thanks @dstokesf5  , I will look into VS code side.
