### ISSUE TITLE
Add/Remove/Update Routes not consistent

### ISSUE THREAD

**Issue by mwardbopp** [F5Networks/f5-declarative-onboarding#298]
### Environment
 * Declarative Onboarding Version: 1.27
 * BIG-IP Version: 16.1

### Summary
Unable to remove routes 

### Steps To Reproduce
For instance if I start with two static routes:
 ```
        "bigiq_route_1": {
            "class": "Route",
            "network": "10.0.1.0/24",
            "gw": "10.1.100.1"
        },
        "bigip_route_2": {
            "class": "Route",
            "network": "10.0.170.0/24",
            "gw": "10.1.100.1"
        }
 ```
I get two routes on the box.
 
If I send another DO declaration with just one route, it will delete the other route. (makes sense)
 
If I send a DO with both routes removed after that, it leaves the one route. (doesn’t make sense) 
 
If I send a DO with both routes back, both routes are there. (makes sense)
 
If I send a DO with both routes removed, both routes stay there.  (doesn’t make sense). 

Also, if I send the following DO I get a rollback
```
        "bigip_route_3": {
            "class": "Route",
            "network": "10.0.170.0/24",
            "gw": "10.1.100.1"
        }

    "message": "invalid config - rolled back",
    "errors": [
        "transaction failed:01070734:3: Configuration error: invalid static route, the dest/netmask pair 10.0.170.0/255.255.255.0 already exists for /Common/bigip_route_2",
        "transaction failed:01070734:3: Configuration error: invalid static route, the dest/netmask pair 10.0.170.0/255.255.255.0 already exists for /Common/bigip_route_2"
```
### Expected Behavior
I expect to be able to delete routes, or declare the routes I want and not to have to worry about the configuration on the box.

### Actual Behavior
DO doesn't ever appear to want to update an existing route (rename the route), or leave the box with no routes.

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this to our internal product backlog as AUTOTOOL-3065.

**Comment by dstokesf5** [comment]
We were able to reproduce this issue with 1.27.0, but not with 1.28.0. Do you experience the same issues when using 1.28.0?
