### ISSUE TITLE
BIG-IQ support in DO

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-declarative-onboarding#3]
**FEATURE REQUEST**

Many of the IQ endpoints are not idempotent creating issues with placing these calls in continuous pipelines with generic rest/uri modules, if DO handled some of the easy-start API and clustering it would make on-boarding this product significantly easier.

**Comment by thomsonjames** [comment]
I agree, I have run into multiple times where this would be required.

**Comment by dstokesf5** [comment]
AUTOTOOL-125 was closed a while ago. Closing this GitHub issue as well.
