### ISSUE TITLE
Records Per Screen	in DO

### ISSUE THREAD

**Issue by difzhao** [F5Networks/f5-declarative-onboarding#301]
### Is your feature request related to a problem? Please describe.
I am looking for a way to configure the Records Per Screen in the declaration file

### Describe the solution you'd like
I would like to see an option to configure Records Per Screen in the declaration file

### Describe alternatives you've considered
Right now I have to manually configure the setting on the GUI but would be overwritten every time I push the DO (for changing other settings)

### Additional context
I am using DO v1.27.0 and my Big-IP is v14.1.4.5 in Azure

**Comment by dstokesf5** [comment]
Thank you for your feedback. Can you provide an example of the tmsh configuration you want to achieve with DO?

**Comment by seattlevine** [comment]
This is controlled by the db var ui.system.preferences.recordsperscreen, so you should be able to set it with this in your declaration (for example)

```
        "dbvars": {
            "class": "DbVariables",
            "ui.system.preferences.recordsperscreen": "25"
        }
```

**Comment by difzhao** [comment]
Thank you @seattlevine! This worked.
