### ISSUE TITLE
Typo on dscHandler.js

### ISSUE THREAD

**Issue by pzolo** [F5Networks/f5-declarative-onboarding#31]
[root@bigip:Active:Standalone] config # grep Proessing /var/config/rest/iapps/f5-declarative-onboarding/nodejs/dscHandler.js
        logger.fine('Proessing DSC declaration.');

Should be Processing

**Comment by focrensh** [comment]
AT-363 for tracking internally

**Comment by dstokesf5** [comment]
Looks like this was resolved a year ago, closing the issue.
