### ISSUE TITLE
GSLBGlobals not processed

### ISSUE THREAD

**Issue by thepowercoders** [F5Networks/f5-declarative-onboarding#311]
### Environment
* Declarative Onboarding Version: 1.27.0
* BIG-IP Version: BIG-IP 15.1.4 Build 0.0.47 Final

### Summary
When a DO declaration is sent including configuration in class GSLBGlobals, it is processed and a "200 OK" is returned. However, the configuration is not updated.

### Steps To Reproduce
1. Submit a DO declaration containing the following:
```json
     "GSLB-settings": {
       "general": {
        "class": "GSLBGlobals",
        "synchronizationEnabled": true,
        "synchronizationGroupName": "my-gslb-configsync"
        }
     }
```

2. Observe a 200 OK response but when checking in GUI, the configuration has not changed from defaults:

### Expected Behavior
Configuration should update.

### Actual Behavior
![Screenshot 2022-05-26 150241](https://user-images.githubusercontent.com/32461620/170503465-e16dd179-7abf-4cff-b9aa-945131f06452.png)

Configuration does not update.

Log seems to only show default configuration:
```
[admin01@network-uks-f5-dns-vm-001:Active:Standalone] ~ # grep synchronizationGroupName /var/log/restnoded/restnoded.log
Thu, 26 May 2022 12:28:05 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /tm/gtm/global-settings/general?%24filter=partition%20eq%20Common&%24select=synchronization%2CsynchronizationGroupName%2CsynchronizationTimeTolerance%2CsynchronizationTimeout%2Cname
Thu, 26 May 2022 12:28:06 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"synchronization":"no","synchronizationGroupName":"default","synchronizationTimeTolerance":10,"synchronizationTimeout":180}
Thu, 26 May 2022 12:55:02 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /tm/gtm/global-settings/general?%24filter=partition%20eq%20Common&%24select=synchronization%2CsynchronizationGroupName%2CsynchronizationTimeTolerance%2CsynchronizationTimeout%2Cname
Thu, 26 May 2022 12:55:04 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"synchronization":"no","synchronizationGroupName":"default","synchronizationTimeTolerance":10,"synchronizationTimeout":180}
Thu, 26 May 2022 12:55:19 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /tm/gtm/global-settings/general?%24filter=partition%20eq%20Common&%24select=synchronization%2CsynchronizationGroupName%2CsynchronizationTimeTolerance%2CsynchronizationTimeout%2Cname
Thu, 26 May 2022 12:55:20 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"synchronization":"no","synchronizationGroupName":"default","synchronizationTimeTolerance":10,"synchronizationTimeout":180}
```

**Comment by dstokesf5** [comment]
@antonywm thank you for your feedback. It appears that you have the class name incorrect. Please review this example: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/declarations/gslb.html?highlight=gslb#configuring-global-gslb-settings-in-a-declaration.

**Comment by dstokesf5** [comment]
I have added this issue to our internal product backlog as AUTOTOOL-3328.

**Comment by thepowercoders** [comment]
any update to this? It's been open almost a year !

**Comment by sunitharonan** [comment]
Hi @thepowercoders, this has been resolved in V1.32.0.

**Comment by thepowercoders** [comment]
ok I will test and come back to you....

**Comment by thepowercoders** [comment]
confirmed fixed. Thank you.
