### ISSUE TITLE
DO - Ability to set multiple management routes upon initial declaration

### ISSUE THREAD

**Issue by Ronnie110755** [F5Networks/f5-declarative-onboarding#338]
The problem is, there is no ability to add 'Management Routes' in plural during the initial Declaration. Not referring to the initial default route as is configured when a device is initially configured with the management ip address and default gateway. But actual management routes as described here:

 [https://support.f5.com/csp/article/K13284](url)

 This is a necessary feature when it comes to proper system administration and is a common practice.

 ### Describe alternatives you've considered

There is no other alternative for automation.  The only other option, non-automated, is making manual changes via the CLI after the initial onboarding.

**Comment by seattlevine** [comment]
DO does support multiple management routes. Here is an example declaration:
```
{
    "class": "Device",
    "schemaVersion": "1.26.0",
    "async": true,
    "Common": {
        "class": "Tenant",
        "mgmtRoute1": {
            "class": "ManagementRoute",
            "gw": "10.10.1.1",
            "network": "10.10.1.0/24",
            "mtu": 0
        },
        "mgmtRoute2": {
            "class": "ManagementRoute",
            "gw": "10.20.1.1",
            "network": "10.20.1.0/24",
            "mtu": 0
        },
        "mySystem": {
            "class": "System",
            "preserveOrigDhcpRoutes": true
        }
    }
}
```

**Comment by mdditt2000** [comment]
@Ronnie110755 where you able to look at @seattlevine example declaration?
