### ISSUE TITLE
GLSB - Add synchronize-zone-files key/value to schema

### ISSUE THREAD

**Issue by KyleTwenty** [F5Networks/f5-declarative-onboarding#377]
In the ‘gslbGlobals’ section of a DO declaration, the current schema does not include a key/value that replicates the check-box in the GUI for “Synchronize DNS Zone Files”. In the bigip_gtm.conf file, it looks like this:

 gtm global-settings general {
      synchronize-zone-files yes
 }
Would like to see this added for clients who use DNS Sync Groups.

**Comment by sunitharonan** [comment]
Created AUTOTOOL-4400 and added to our backlog.

**Comment by mdditt2000** [comment]
Closed Resolved in 1.46.0
Release Notes | https://github.com/F5Networks/f5-declarative-onboarding/releases/tag/v1.46.0
