### ISSUE TITLE
DO 1.4.1 schemaVersion broken

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-declarative-onboarding#39]
DO f5-declarative-onboarding-1.4.1-1.noarch installed directly on bigip will fail the schemeVersion in a declaration of anything greater than 1.3.0.

{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json",
    "schemaVersion": "1.4.1",
    "class": "Device",
    "async": true,
    "label": "Onboard BIG-IP into an HA Pair"
}

results in:

{"code":400,"message":"java.net.ProtocolException: status:400, body:{\"id\":\"8ba0f4bf-dde1-4215-84f3-0d8f598519ba\",\"selfLink\":\"https://localhost/mgmt/shared/declarative-onboarding/task/8ba0f4bf-dde1-4215-84f3-0d8f598519ba\",\"code\":400,\"status\":\"ERROR\",\"message\":\"bad declaration\",\"errors\":[{\"keyword\":\"enum\",\"dataPath\":\".declaration.schemaVersion\",\"schemaPath\":\"#/properties/schemaVersion/enum\",\"params\":{\"allowedValues\":[\"1.3.0\",\"1.2.0\",\"1.1.0\",\"1.0.0\"]},\"message\":\"should be equal to one of the allowed values\"}],\"result\":{\"class\":\"Result\",\"code\":400,\"status\":\"ERROR\",\"message\":\"bad declaration\",\"errors\":[{\"keyword\":\"enum\",\"dataPath\":\".declaration.schemaVersion\",\"schemaPath\":\"#/properties/schemaVersion/enum\",\"params\":{\"allowedValues\":[\"1.3.0\",\"1.2.0\",\"1.1.0\",\"1.0.0\"]},\"message\":\"should be equal to one of the allowed values\"}]},\"declaration\"

**Comment by seattlevine** [comment]
There are no schema changes so we have left the schemaVersion unchanged. With DO 1.5.0, we decided that it would be less confusing for customers just to keep the schemaVersion in sync with the code version.

**Comment by jmcalalang** [comment]
theoretically, I knew this could happen, however, it isn't called out anywhere, it was a trial and error test. Did I miss a document that calls out this for specifically 1.4.x?

**Comment by seattlevine** [comment]
No, but as soon as 1.5.0 is out, this problem will go away.

**Comment by seattlevine** [comment]
Resolved in 1.5.0
