### ISSUE TITLE
Question about feature "Added support for using Authorized Keys in declarations."

### ISSUE THREAD

**Issue by zongzw** [F5Networks/f5-declarative-onboarding#44]
Hi, I noticed in 1.5.0, we add a new feature: "Added support for using Authorized Keys in declarations."
But I'm not sure the details and usage about this feature. Could you please give me some references for it?

From the repo docs, I just found the following relevant about authorization, not sure which one mentions to.

1. Authentication and Authorization: https://github.com/F5Networks/f5-declarative-onboarding/blob/master/docs/authentication.rst
2. Adding Basic Authentication for accessing DO container: https://github.com/F5Networks/f5-declarative-onboarding/blob/master/docs/do-container.rst#adding-basic-authentication
3. targetTokens(access onboarding target with token): https://github.com/F5Networks/f5-declarative-onboarding/blob/master/schema/remote.schema.json#L86

**Comment by zongzw** [comment]
found it, thanks. 
Should be here: https://github.com/F5Networks/f5-declarative-onboarding/blob/master/schema/latest/system.schema.json#L177

**Comment by ansmithf5** [comment]
We also have an example here:
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/examples.html?highlight=keys#example-12-adding-public-ssh-keys-to-a-declaration

Please let us know if you have any questions.
