### ISSUE TITLE
DO 1.5.0 could not be installed in BIGIP VE 13.1.1.4 and 14.1.3

### ISSUE THREAD

**Issue by jikui** [F5Networks/f5-declarative-onboarding#48]
hi, 
1) We are trying to install the DO version 1.5.0  rpm into bigip ve Instance with versions of 13.1.1.4 and 14.1.3 while the installation could not succeed.

2) We are also trying to install the RPM via the webui, it still could not succeed with the following error page.
"Package installation failed with error: Task: /mgmt/shared/iapp/package-management-tasks/55d8928a-65b7-4b7a-b159-2b7573581639 failed to complete, with error message: Failed to analyze /var/config/rest/downloads/f5-declarative-onboarding-1.5.0-11.noarch.rpm - java.lang.Exception: Failed to read /var/config/rest/downloads/f5-declarative-onboarding-1.5.0-11.noarch.rpm"

3) we checked the the rpm DOES exist at bigip already while the installation failed.
[root@host-10-250-15-142:NO LICENSE:Standalone] downloads # ls -al
total 80
drwxr-x---.  3 root apache  4096 Jul  3 20:11 .
drwxr-xr-x. 13 root root    4096 Jul  3 20:06 ..
-rw-r-----.  1 root apache 65772 Jul  3 20:11 f5-declarative-onboarding-1.5.0-11.noarch.rpm
drwxr-xr-x.  2 root root    4096 Jul  3 20:11 tmp

4) We  also followed the instructions from https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/installation.html#uploadcurl to upload and install the DO rpm, every time the installation will fail.  

[11:14:18] pei:Downloads git:(jikui*) $ curl -k -u  admin:P@ssw0rd123 https://10.250.15.142/mgmt/shared/iapp/package-management-tasks/15e9eead-2ea4-4f79-9171-6b8cf7e53e46
{"packageFilePath":"/var/config/rest/downloads/f5-declarative-onboarding-1.5.0-11.noarch.rpm","operation":"INSTALL","id":"15e9eead-2ea4-4f79-9171-6b8cf7e53e46","status":"FAILED","startTime":"2019-07-03T20:14:09.674-0700","endTime":"2019-07-03T20:14:09.864-0700","errorMessage":"Failed to analyze /var/config/rest/downloads/f5-declarative-onboarding-1.5.0-11.noarch.rpm - java.lang.Exception: Failed to read /var/config/rest/downloads/f5-declarative-onboarding-1.5.0-11.noarch.rpm","userReference":{"link":"https://localhost/mgmt/shared/authz/users/admin"},"identityReferences":[{"link":"https://localhost/mgmt/shared/authz/users/admin"}],"ownerMachineId":"8787a972-4774-4384-8c29-15dc3e70c91e","generation":3,"lastUpdateMicros":1562210049864842,"kind":"shared:iapp:package-management-tasks:iapppackagemanagementtaskstate","selfLink":"https://localhost/mgmt/shared/iapp/package-management-tasks/15e9eead-2ea4-4f79-9171-6b8cf7e53e46"}%

Please help on this.

Thanks in advance.

Jikui

**Comment by jikui** [comment]
The rpm package I used is invalidate.

**Comment by RobCupples** [comment]
Thank you for your report.  I'm glad you figured it out.
