### ISSUE TITLE
support overwrite license for bigiq license 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-declarative-onboarding#5]
support the "overwrite" flag for bigiq licensing. 
the use case is to issue a license to a device that's already licensed. for example for scale up or for added functionality. 

looking at the scheme, it looks like the "overwrite" protpery is only part of "regkey" license.
when i send a new declaration with a different sku1_keyword than the one installed it doesn't change the license.
when i try to add this property to a declaration with bigiq license i get the following error:

11:34:37         "errors": [
11:34:37             {
11:34:37                 "dataPath": ".Common['myLicense']", 
11:34:37                 "keyword": "additionalProperties", 
11:34:37                 "message": "should NOT have additional properties", 
11:34:37                 "params": {
11:34:37                     "additionalProperty": "overwrite"
11:34:37                 }, 
11:34:37                 "schemaPath": "#/allOf/0/then/else/additionalProperties"
11:34:37             }
11:34:37         ], 
11:34:37         "message": "bad declaration", 
11:34:37         "status": "ERROR"

**Comment by seattlevine** [comment]
We are currently working on this and it will be in DO 1.3

**Comment by seattlevine** [comment]
Resolved in 1.3.0-beta.1
