### ISSUE TITLE
Feature Request: Add /tm/sys

### ISSUE THREAD

**Issue by Mikej81** [F5Networks/f5-declarative-onboarding#50]
Expanding upon sys db and global-settings, there should be a way to set sys vars, specifically sshd, httpd.  Stretch of software, snmp, daemon-log-settings.

**Comment by thomsonjames** [comment]
would also want 
sys global-settings gui-setup disabled

**Comment by focrensh** [comment]
Some of the requested objects in the list have a large amount of sub-options. Using httpd as an example: Are each of these options needed for manipulation currently?

```
  allow                         log-level                     ssl-ca-cert-file              ssl-ocsp-responder-timeout
  auth-name                     max-clients                   ssl-certchainfile             ssl-ocsp-response-max-age
  auth-pam-dashboard-timeout    redirect-http-to-https        ssl-certfile                  ssl-ocsp-response-time-skew
  auth-pam-idle-timeout         request-body-max-timeout      ssl-certkeyfile               ssl-port
  auth-pam-validate-ip          request-body-min-rate         ssl-ciphersuite               ssl-protocol
  description                   request-body-timeout          ssl-include                   ssl-verify-client
  fastcgi-timeout               request-header-max-timeout    ssl-ocsp-default-responder    ssl-verify-depth
  hostname-lookup               request-header-min-rate       ssl-ocsp-enable               {
  include                       request-header-timeout        ssl-ocsp-override-responder
```

**Comment by Mikej81** [comment]
Having everything would be amazing, but at a minimum, and not limited to, I would say:

httpd/allow
httpd/max-clients
httpd/auth-pam-idle-timeout
httpd/ssl-ciphersuite
https/ssl-protocol

sshd/inactivity-timeout
sshd/banner
sshd/banner-text
sshd/include [example:  "Protocol 2\r\nMaxAuthTries 3\r\nCiphers aes128-ctr,aes192-ctr,aes256-ctr\r\nMACs hmac-sha1,hmac-ripemd160\r\nLoginGraceTime 1m\r\nMaxStartups 5"]

**Comment by focrensh** [comment]
SSHd: AUTOTOOL-573

HTTPD: AUTOTOOL-574

**Comment by thomsonjames** [comment]
It looks like from the logs it does gui-setup disabled already behind the scenes without being asked so I think I'm covered on that one.

Wed, 31 Jul 2019 03:00:08 GMT - fine: [f5-declarative-onboarding: declarationHandler.js] Processing declaration.
Wed, 31 Jul 2019 03:00:08 GMT - fine: [f5-declarative-onboarding: restWorker.js] modify localhost /tm/sys/global-settings {"guiSetup":"disabled"}

**Comment by jdherre** [comment]
Can we add SSHD/allow as well it's nice to have access lists defined for both services. 

example from my HTTPD block and need to mirror it in SSHD if possible. 
"allow": [
                "10.20.0.0/16",
                "40.66.128.0/17",
                "141.251.224.0/19",
                "129.75.192.0/18",
                "192.32.128.0/17"
            ],

**Comment by dstokesf5** [comment]
This was added several releases ago. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.
