### ISSUE TITLE
Documentation: How do you remove a declaration?

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-declarative-onboarding#52]
I don't see any documentation on how to remove the DO declaration.

I tried a DELETE, but can't figure out what it wants.

https://{{bigip_a_mgmt}}/mgmt/shared/declarative-onboarding/config/
{
    "id": "ff1ac90d-ef17-47dd-b78d-aecb889515b5",
    "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/ff1ac90d-ef17-47dd-b78d-aecb889515b5"
}

Response:

{
    "code": 400,
    "message": "status:400, body:id must be specified for DELETE",
    "originalRequestBody": "id must be specified for DELETE",
    "referer": "10.1.0.220",
    "restOperationId": 5819965,
    "kind": ":resterrorresponse"
}

**Comment by focrensh** [comment]
Per @seattlevine 

DELETE is not currently supported for tasks. The ‘config’ endpoint is generally for use by BIG-IQ for when it deletes a VE that it created. DO stores the original configuration of each device it configures and this data can be deleted when the VE is deleted.
 
Generally, if DO appears to be stuck (nothing new is showing in /var/log/restnoded/restnoded.log and the status is RUNNING), you can re-POST without doing a DELETE. If you have repro steps for getting to this state, please file an issue.
