### ISSUE TITLE
Documentation: Improve Route domain json

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-declarative-onboarding#54]
Just to make it more understandable, I'd suggest using a more realistic setup:
1) using 1.1 for vlan
2) since you're tagging the vlan, add the tag in the vlan definition
3) proper subnetting in the routes section, make the network statement make sense.
4) Match IP's up in the route statement to make sense with the self IP

https://github.com/F5Networks/f5-declarative-onboarding/blob/master/examples/routeDomains.json

[rd-sample.json.txt](https://github.com/F5Networks/f5-declarative-onboarding/files/3449668/rd-sample.json.txt)

Attached a suggestion

**Comment by JosephPJordan** [comment]
Thanks for the feedback James, we've updated the example per your request, and it's now live: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/bigip-examples.html#adding-route-domains-to-a-declaration
