### ISSUE TITLE
dns resolver support 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-declarative-onboarding#6]
i couldn't find a way to configure dns resolver,
Add support for dns resolver, 
https://devcentral.f5.com/wiki/iControlREST.APIRef_tm_net_dns-resolver.ashx 

use case is using bot defense (asm). it requires a dns resolver to be configured. 
https://support.f5.com/csp/article/K00736342

**Comment by seattlevine** [comment]
Tracking with internal issue 177

**Comment by tizianorosato-gr** [comment]
Interested on dns resolver too.

Dns resolver is fundamental config item when confuring F5 as a forward proxy.

**Comment by dstokesf5** [comment]
This was resolved in the 1.14.0 release.
