### ISSUE TITLE
Management Route class does not work

### ISSUE THREAD

**Issue by assareh** [F5Networks/f5-declarative-onboarding#60]
DO 1.6
system is configured with static mgmt ip of 10.1.1.252/24 or 10.1.1.253/24
there is no mgmt route configured
systems can ping 10.1.1.2

attempting to use management route class as follows:

        "managementRoute": {
            "class": "ManagementRoute",
            "gw": "10.1.1.2",
            "network": "default"
        },

Wed, 14 Aug 2019 23:39:42 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: 01070750:3: Route gateway address does not match destination's address type (inet vs. inet6). tries left: 30

attempting to use management route class as follows:

        "managementRoute": {
            "class": "ManagementRoute",
            "gw": "10.1.1.2",
            "network": "0.0.0.0/0"
        },

Wed, 14 Aug 2019 23:55:35 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: 01070750:3: Route gateway address does not match destination's address type (inet vs. inet6). tries left: 30

attempting to use management route class as follows:

        "managementRoute": {
            "class": "ManagementRoute",
            "gw": "10.1.1.2",
            "network": "default",
            "mtu": 1500,
            "type": "interface"
        },

A management route object is created on BIG-IP but without the gateway:

sys management-route managementRoute {
    mtu 1500
    network default
    type interface
}

attempting to use management route class as follows:

        "managementRoute": {
            "class": "ManagementRoute",
            "gw": "10.1.1.2",
            "network": "default",
            "mtu": 1500
        },

Thu, 15 Aug 2019 00:13:59 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: 01070750:3: Route gateway address does not match destination's address type (inet vs. inet6). tries left: 30

**Comment by seattlevine** [comment]
This is a bug that will be fixed in 1.7

**Comment by dstokesf5** [comment]
Version 1.7 was released for a fix for this. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.
