### ISSUE TITLE
Problem with Management Route

### ISSUE THREAD

**Issue by s-archer** [F5Networks/f5-declarative-onboarding#61]
I have this, before DO is deployed:
 
"list sys management-route
sys management-route default {
    description customized-by-vmware
    gateway 172.30.107.254
    network default
}"
 
I have now tried three methods:
 
- 1. Don’t specify a management route in the DO JSON:
 
"Thu, 15 Aug 2019 15:37:14 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Checking ManagementRoute.
Thu, 15 Aug 2019 15:37:14 GMT - finest: [f5-declarative-onboarding: restWorker.js] /tm/sys/management-route/~Common~0 does not exist, creating
Thu, 15 Aug 2019 15:37:14 GMT - fine: [f5-declarative-onboarding: restWorker.js] create localhost /tm/sys/management-route {"name":"0","partition":"Common"}
Thu, 15 Aug 2019 15:37:14 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {"code":400}
Thu, 15 Aug 2019 15:37:14 GMT - finest: [f5-declarative-onboarding: restWorker.js] typeof err object
Thu, 15 Aug 2019 15:37:14 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: 01070088:3: The requested object name (/Common/0) is invalid. tries left: 30"
 
- 2. Specify a management route (managementRoute) in DO JSON, just like in the examples on clouddocs:
 
"Thu, 15 Aug 2019 18:12:03 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Checking ManagementRoute.
Thu, 15 Aug 2019 18:12:04 GMT - finest: [f5-declarative-onboarding: restWorker.js] /tm/sys/management-route/~Common~managementRoute does not exist, creating
Thu, 15 Aug 2019 18:12:04 GMT - fine: [f5-declarative-onboarding: restWorker.js] create localhost /tm/sys/management-route {"name":"managementRoute","partition":"Common","gw":"172.30.107.254","network":"default","mtu":1500,"type":"interface"}
Thu, 15 Aug 2019 18:12:04 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {"code":400}
Thu, 15 Aug 2019 18:12:04 GMT - finest: [f5-declarative-onboarding: restWorker.js] typeof err object
Thu, 15 Aug 2019 18:12:04 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: 01070734:3: Configuration error: invalid Management Route, the dest/netmask pair 0.0.0.0/0.0.0.0 already exists for /Common/default tries left: 30"
 

- 3. Specify a management route (/Common/default) in DO JSON, as suggested by Lucy@F5:
 
"Thu, 15 Aug 2019 18:27:25 GMT - finest: [f5-declarative-onboarding: restWorker.js] Got onboarding request.
Thu, 15 Aug 2019 18:27:25 GMT - info: [f5-declarative-onboarding: restWorker.js] Bad declaration: [{"keyword":"pattern","dataPath":".declaration.Common","schemaPath":"#/properties/Common/propertyNames/pattern","params":{"pattern":"^[A-Za-z][0-9A-Za-z_-]{0,47}$"},"message":"should match pattern \"^[A-Za-z][0-9A-Za-z_-]{0,47}$\"","propertyName":"/Common/default"},{"keyword":"propertyNames","dataPath":".declaration.Common","schemaPath":"#/properties/Common/propertyNames","params":{"propertyName":"/Common/default"},"message":"property name '/Common/default' is invalid"}]"
 
I included it like this:
 
      "/Common/default": {
        "class": "ManagementRoute",
        "gw": "{{ net_mgmt.gw }}",
        "network": "default",
        "mtu": 1500,
        "type": "interface"
      },

All fail.  Help appreciated.

**Comment by seattlevine** [comment]
i: I'm not sure where that 'name: "0"' is coming from. Before you run DO, what is the output of running this locally on the BIG-IP:
curl -sku admin: https://localhost/mgmt/tm/net/managementRoute'
ii. This is a bug that will be fixed in 1.7.0
iii: You shouldn't have "/Common/default", just "default" as the object name. Also, you can't specify 'type' and 'gw' at the same time. Our example is incorrect - we'll get that fixed. However, the bug in 1.6.0 prevents gw from working at all.

**Comment by BarryKembleF5** [comment]
Hi,

Do we have a date for the release of 1.7.0 to fix the issue?

Thanks.

**Comment by dstokesf5** [comment]
Version 1.7 was released for a fix for this. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.

**Comment by mahuron** [comment]
@hvaneenoo @dstokesf5 

Either this was improperly verified or it has regressed.  Under 1.20.0, an attempt to add default management route elicits the following:

```
Configuration error: invalid Management Route, the dest/netmask pair 0.0.0.0/0.0.0.0 already exists for /Common/default'
```

class = "ManagementRoute", network = "default", etc.  Eliminating the offending route results in successful call.  Adding the route by hand works.

Seems management route validation is colliding with dataplane routing table.? What's worse, DO proceeds to apply my other, non-default routes, blowing out the DHCP provided default route.  I will have to resort to hacks (0/16 + 128/16 routes) to work around this.

Please advise and/or reopen.  Can open support case if that avenue is preferred.

Thank you.

**Comment by dstokesf5** [comment]
@mahuron Can you please create a new GitHub issue to describe the problem you are seeing? I think that will be the easiest way for us to track your issue. Feel free to reference this issue in the new one.
