### ISSUE TITLE
Licensing from big-iq does not work in 1.6

### ISSUE THREAD

**Issue by techoover** [F5Networks/f5-declarative-onboarding#63]
issue with DO 1.6 (f5-declarative-onboarding-1.6.0-1.noarch.rpm) and licensing from BIG-IQ? BIG-IQ is on version 6.1
Declaration works with DO version 1.3
from /var/log/restnoded/restnoded.log
Wed, 21 Aug 2019 13:27:17 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Getting license provider
Wed, 21 Aug 2019 13:27:18 GMT - finest: [f5-declarative-onboarding: systemHandler.js] using api type REG_KEY
Wed, 21 Aug 2019 13:27:18 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Getting license from provider.
Wed, 21 Aug 2019 13:27:18 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Getting BIG-IP license pool UUID.
Wed, 21 Aug 2019 13:27:18 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Got pool UUID: 3242ec83-5012-44a3-8f82-7e63af58766b
Wed, 21 Aug 2019 13:27:18 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Getting reg keys in pool
Wed, 21 Aug 2019 13:27:18 GMT - fine: [f5-declarative-onboarding: systemHandler.js] <regkey removed> is not active
Wed, 21 Aug 2019 13:27:18 GMT - info: [f5-declarative-onboarding: systemHandler.js] {}
Wed, 21 Aug 2019 13:27:18 GMT - finest: [f5-declarative-onboarding: systemHandler.js] tryUntil: got error {}
Wed, 21 Aug 2019 13:27:18 GMT - finest: [f5-declarative-onboarding: systemHandler.js] typeof err object
Wed, 21 Aug 2019 13:27:18 GMT - finer: [f5-declarative-onboarding: systemHandler.js] tryUntil error: Cannot read property 'registrationKey' of undefined tries left: 30
Wed, 21 Aug 2019 13:27:18 GMT - finest: [f5-declarative-onboarding: systemHandler.js] tryUntil: retryOrReject: numRemaining: 30 , code: {} , message: Cannot read property 'registrationKey' of undefined

**Comment by seattlevine** [comment]
This will be fixed in 1.7.0

**Comment by dstokesf5** [comment]
Version 1.7 was released for a fix for this. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.
