### ISSUE TITLE
Declarative Onboarding - Trunk Support

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-declarative-onboarding#64]
## Feature Request ##

Looking for trunk support in DO for hardware, this isn't included in any documentation that is should or shouldn't be added as a feature.

There are notes about "Stiching" as a feature that won't be configured, however the definition of that isn't clear either.

Tracking for @jamesjrwood, @yossi-r

**Comment by dstokesf5** [comment]
DO has added trunking support that will be available in the 1.7.0 release.

**Comment by jmcalalang** [comment]
Excellent, thanks Daniel!

**Comment by dstokesf5** [comment]
This was fixed in a previous version of DO. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.
