### ISSUE TITLE
Load Masterkey

### ISSUE THREAD

**Issue by codygreen** [F5Networks/f5-declarative-onboarding#69]
##### ISSUE TYPE

 - Feature Idea

Add feature to load a BIG-IP master key so standalone ASM instance can use the same tscookie and configuration.

https://devcentral.f5.com/s/articles/working-with-masterkeys

##### BIG-IP Command
f5mku -r abcdefg12345==

**Comment by dstokesf5** [comment]
If Declarative Onboaring runs that command through bash, the masterkey will end up in the audit log. Do you know if there is a way to load the masterkey through iControl REST that does not involve using the bash endpoint?

**Comment by codygreen** [comment]
No, this is something I will discuss with the ASM Product Manager.

**Comment by codygreen** [comment]
@dstokesf5, this request has come back up in another opportunity.  There is a method in tmsh do perform this: https://clouddocs.f5.com/cli/tmsh-reference/latest/modules/sys/sys_crypto_master-key.html. I'm having difficulty finding the API documentation for this endpoint though.

**Comment by codygreen** [comment]
@dstokesf5, I was wrong... that TMSH command and API endpoint are for the crypto master key and not the ASM master key.

**Comment by dstokesf5** [comment]
I have added this request to our internal product backlog as AUTOTOOL-1385. However, it is blocked until we find a way to load the ASM master key that does not involve using the bash endpoint.

**Comment by amolari** [comment]
@dstokesf5 could you please unblock this issue?
Actual [F5 recommendations](https://support.f5.com/csp/article/K73034260) are to use the `tmsh modify sys crypto master-key prompt-for-password` command to set the master key. The master key value won't show up in the audit log, as seen here:

```
Dec  3 13:46:42 xxx notice mcpd[4697]: 01070417:5: AUDIT - client tmsh, tmsh-pid-23951, user admin - transaction #27388322-1 - object 0 - modify { master_key { master_key_master_key "***" } } [Status=Command OK]
Dec  3 13:46:42 xxx notice tmsh[23951]: 01420002:5: AUDIT - pid=23951 user=admin folder=/Common module=(tmos)# status=[Command OK] cmd_data=modify sys crypto master-key prompt-for-password
```
Note: tested on BIG-IP 16.1.2 and 14.1.4

**Comment by dstokesf5** [comment]
@amolari The problem is that DO uses iControl REST to apply the configuration. As far as I can tell, the only way to apply that tmsh operation with iControl REST is to use the bash endpoint. The entire payload of calls to the bash endpoint are put into the audit log uncensored.

**Comment by delgadillo22** [comment]
We've researched this and determined that there isn't a way to do this without exposing the key in the audit log. Cannot commit because this would introduce a security vulnerability. Closing this issue.
