### ISSUE TITLE
Does not remove SelfIP and VLAN

### ISSUE THREAD

**Issue by gtownsie** [F5Networks/f5-declarative-onboarding#7]
Sent an initial POST with VLAN and Self definitions, everything worked as expected.  After removing the VLAN and SELF definitions from the post, and resubmitting, the error below was displayed:

{
    "code": 422,
    "status": "ERROR",
    "message": "invalid config - rolled back",
    "errors": [
        "01070265:3: The VLAN (/Common/external) cannot be deleted because it is in use by a self IP (/Common/external-self)."
    ],
    "declaration": {
        "schemaVersion": "1.1.0",
        "class": "Device",
        "Common": {
            "class": "Tenant",

**Comment by seattlevine** [comment]
Tracking with internal issue 217

**Comment by kaustriaf5** [comment]
Hi @gtownsie , can you please verify if this is reproducible with clean BIG-IP device and just posting a decl with selfIp and vlan and then posting without the selfip and vlan?

Is it possible you had a manually configured some vlans/selfips at some point?

**Comment by kaustriaf5** [comment]
Was able to repro this, and fix in progress.

**Comment by seattlevine** [comment]
Resolved in 1.3.1
