### ISSUE TITLE
Some onboarding configuration is lost later after onboarded.

### ISSUE THREAD

**Issue by zongzw** [F5Networks/f5-declarative-onboarding#71]
I found on the onboarded BIG-IP VE in OpenStack, some configuration lost soon. 
For example, I onboard the BIG-IP VE with hostname `81eed50f-4219-40ba-86e6-73decb293769.openstack.local`, it takes effect just after DO done, but later after some time, the hostname lost and changed back to initial `host-10-250-16-128.openstacklocal`.  

Could you please help to check this issue?

**Comment by dstokesf5** [comment]
DO should not be changing anything if you are not sending it a declaration. Is it possible that something else, such as OpenStack, is manipulating the hostname?

Are you doing anything to your BIG-IP after you have run DO, but before the hostname reverted? Perhaps rebooting the BIG-IP?

Also how long is "some time"? Minutes? Hours? Days?

**Comment by zongzw** [comment]
@dstokesf5 sorry that I cannot answer any of your questions.. I at least encountered 3 times this case. I may have to check this situation more times. 
By the way, you are the expert for BIG-IP. When the onboarding(or any changes happen), BIG-IP should have some log(or other hints logged down), is it correct?

**Comment by dstokesf5** [comment]
The BIG-IP has many log files. Declarative Onboarding's output goes to `/var/log/restnoded/restnoded.log`.

**Comment by zongzw** [comment]
Thanks, I'll provision several VE and check the occasions again.

**Comment by zongzw** [comment]
After observation for a dozen days, dozen times, I didn't encounter this situation again. Apologize for chaos. Close it.
