### ISSUE TITLE
[RFE] "tenant" attribute for License class

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-declarative-onboarding#72]
### Summary

BIG-IQ now supports the "tenant" attribute when requesting license assignment. Please add this to the schema. 

### Justification
For the purpose of identifying and matching an assigned licensed to a BIG-IP user based on a user-defined unique identifier. 

### Reference
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/big-iq-licensing.html

/mgmt/cm/device/tasks/licensing/pool/member-management/example

> {
> 
>     "items": [
> 
>         {
> 
>             "licensePoolName": "example string",
> 
>             "command": "example string",
> 
>             "address": "example string",
> 
>             "port": 2147483647,
> 
>             "user": "example string",
> 
>             "password": "example string",
> 
>             "macAddress": "example string",
> 
>             "hypervisor": "example string",
> 
>             "tenant": "example string",  <----------------!!!!!!!!!!!!!!!!
> 
>             "assignmentType": "MANAGED",
> 
>             "skuKeyword1": "example string",
> 
>             "skuKeyword2": "example string",
> 
>             "unitOfMeasure": "example string",
> 
>             "chargebackTag": "example string",
> 
>             "licenseAssignmentReference": {
> 
>                 "link": "http://host:port/path/to/resource",
> 
>                 "isSubcollection": false
> 
>             },
> 
>             "licenseText": "example string",
> 
>             "currentStep": "GET_LICENSE",
> 
> ----snip----

**Comment by dstokesf5** [comment]
Can you please provide additional documentation on this new BIG-IQ tenant feature so we can better understand how it works?

**Comment by dstokesf5** [comment]
Added to our internal product backlog as AUTOTOOL-1635.

**Comment by dstokesf5** [comment]
This issue should be resolved in the 1.15.0 release.
