### ISSUE TITLE
dbVars doesn't take precedence over managementRoute

### ISSUE THREAD

**Issue by garyluf5** [F5Networks/f5-declarative-onboarding#74]
When making a single DO REST call, the dbVar doesn't take precedence over the managementRoute, therefore it returns an error. The only work around is to make two DO calls: 1) set the dbVars; 2) set the managementRoute 

        "managementRoute": {
            "class": "ManagementRoute",
            "gw": "1.2.3.4",
            "network": "169.254.169.254",
            "mtu": 1500
        },
        "dbVars": {
            "class": "DbVariables",
            "config.allow.rfc3927": "enable"
        }

**Comment by dstokesf5** [comment]
I was able to successfully configure a management route using the following declaration:
```json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "managementRoute": {
            "class": "ManagementRoute",
            "gw": "1.2.3.4",
            "network": "169.254.169.254",
            "mtu": 1500
        },
        "dbVars": {
            "class": "DbVariables",
            "config.allow.rfc3927": "enable"
        }
    }
}
```

I made sure that config.allow.rfc3927 was set to "disable" before applying the declaration.

What version of DO and BIG-IP are you using?

**Comment by garyluf5** [comment]
I believe i was using 1.13.0. I will use the latest and give it a try again. Thanks.


Gary
________________________________

**Comment by garyluf5** [comment]
Please close this issue, it appears if I wait a little while after install DO, then it works. It must be some timing issue.
