### ISSUE TITLE
RFE - Enhance DO to prevent AWS hostname updates via dhclient 

### ISSUE THREAD

**Issue by btully** [F5Networks/f5-declarative-onboarding#76]
We are currently running into an issue in AWS where a DO specified hostname is not being maintained on a BIG-IP instance.  It appears that AWS is overwriting our device hostname via dhclient even though dhclient is disabled in the db settings.  It would be great if DO provided a configuration mechanism to prevent this situation.

**Comment by ikauzak** [comment]
I had this same issue before. I managed to get it working after fixing my DO json file.

Looks like it had a problem with creating an user object and it rolled back the rests of the DO configurations.

If you manage to GET ( `https://<BIG-IP>/mgmt/shared/declarative-onboarding`), you will see a "selfLink" line. Then you should try to GET that URL and see if there is any issue.

Mine looked like this:
```
{
    "id": "4fcdcc04-0c5c-442d-8e1f-dfe46e145705",
    "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/4fcdcc04-0c5c-442d-8e1f-dfe46e145705",
    "result": {
        "class": "Result",
        "code": 200,
        "status": "OK",
        "message": "success"
    },
``` 
Of course, you need to change the `localhost` by your dns or bigip's name when using GET to check results.

Hope it helped!

**Comment by dstokesf5** [comment]
@btully What DB settings are you trying to set?

I have created an internal product backlog item AT-807 to apply the work around found in [K45728203](https://support.f5.com/csp/article/K45728203) when a hostname is specified in a DO declaration.

**Comment by dstokesf5** [comment]
This was resolved a few versions ago. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.
