### ISSUE TITLE
Error Creating Self-IP

### ISSUE THREAD

**Issue by gtownsie** [F5Networks/f5-declarative-onboarding#8]
When creating a Self-IP with the name: P02510.11.0.5, I receive the following error: 

Need to modify the pattern match to include a "." tested from the GUI of the bigip and a "." was allowed.

{
    "code": 400,
    "status": "ERROR",
    "message": "bad declaration",
    "errors": [
        {
            "keyword": "pattern",
            "dataPath": ".Common",
            "schemaPath": "#/properties/Common/propertyNames/pattern",
            "params": {
                "pattern": "^[A-Za-z][0-9A-Za-z_-]{0,47}$"
            },
            "message": "should match pattern \"^[A-Za-z][0-9A-Za-z_-]{0,47}$\"",
            "propertyName": "P2510.11.0.5"
        },
        {
            "keyword": "propertyNames",
            "dataPath": ".Common",
            "schemaPath": "#/properties/Common/propertyNames",
            "params": {
                "propertyName": "P2510.11.0.5"
            },
            "message": "property name 'P2510.11.0.5' is invalid"
        }
    ],

**Comment by gtownsie** [comment]
Here is the json body for the SelfIp 
        "P2510.11.0.5": {
            "class": "SelfIp",
            "address": "10.11.0.5/24",
            "vlan": "P025-1025-PRD",
            "allowService": "default",
            "trafficGroup": "traffic-group-local-only"
        },

**Comment by seattlevine** [comment]
We'll have to think about this one. While legal JSON, a '.' in a JSON property can cause parsing issues because it is difficult to tell the difference between:
```
{
    "my.self.ip": "1.2.3.4"
}
```
and
```
{
    "my": {
        "self": {
            "ip": "1.2.3.4"
        }
    }
}
```
Tracking with internal issue 216

**Comment by delgadillo22** [comment]
We concluded not to support "." in names within AS3 due to concerns about implications for DevOps integrations. 

Same will apply to DO for the same reasons and for consistency across the Automation Toolchain.
