### ISSUE TITLE
/mgmt/shared/declarative-onboarding/example does not work

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-declarative-onboarding#82]
Official docs show to use /example to see an example declaration, but an error is returned that no example is available.

**Comment by dstokesf5** [comment]
Confirmed that this endpoint broke in the 1.8.0 release. I have created internal product backlog item AUTOTOOL-904 to track the issue.

**Comment by dstokesf5** [comment]
Version 1.9.0 was released with a fix for this. Closing this issue. If you are still experiencing a problem with the latest version, please reopen the issue or create a new one.
