### ISSUE TITLE
DO Support for Mac Masquerading

### ISSUE THREAD

**Issue by ChrisNelsonF5** [F5Networks/f5-declarative-onboarding#96]
Hello - 

Based on the schema ref, there's no support for mac masquerading - can we get it added?

**Comment by dstokesf5** [comment]
Is this the MAC masquerading features you wish to configure with DO?
https://support.f5.com/csp/article/K13502

**Comment by ChrisNelsonF5** [comment]
Yes


Chris Nelson | Field Systems Engineer - Dallas
Mobile: (214) 288-6653
Email: c.nelson@f5.com
https://www.meetup.com/F5DFWUG/
________________________________

**Comment by tizianorosato-gr** [comment]
I'm quite interested on this feature too.

**Comment by dstokesf5** [comment]
Thank you for your feedback. This has been added to our internal product backlog as AUTOTOOL-1322.

**Comment by dstokesf5** [comment]
@tizianorosato-gr, @ChrisNelsonF5, Are you interested in specifying an arbitrary MAC addresses, or are you following the recommendations in [K3523](https://support.f5.com/csp/article/K3523)?

**Comment by ChrisNelsonF5** [comment]
Following the article. Thanks!


Chris Nelson via mobile | Field Systems Engineer - Dallas
Mobile: (214) 288-6653
Email: c.nelson@f5.com
https://www.meetup.com/F5DFWUG/
________________________________

**Comment by tizianorosato-gr** [comment]
Following the article for sure

Tiziano

**Comment by dstokesf5** [comment]
Thank you for the feedback. We will look into automating the process from the knowledge article instead of expecting the user to provide a MAC address.

**Comment by tizianorosato-gr** [comment]
Hi Daniel,

Just thinking that in a vcmp scenario or when using multiple traffic-group you have to use multiple mac-masquerade.

Tiziano

**Comment by dstokesf5** [comment]
This issue has been resolved as part of the 1.13.0 release.
