### ISSUE TITLE
location of base.schema.json ?

### ISSUE THREAD

**Issue by nergalex** [F5Networks/f5-declarative-onboarding#97]
base.schema.json is no longer located [here](https://github.com/F5Networks/f5-declarative-onboarding/tree/master/schema) as described [here](https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/validate.html?highlight=schema).
Where is it located now please?
Or how could I generate it from source archive?

**Comment by seattlevine** [comment]
The base.schema.json is now located [here](https://github.com/F5Networks/f5-declarative-onboarding/blob/master/src/schema/latest/base.schema.json)

**Comment by seattlevine** [comment]
Leaving this open so we can update docs.

**Comment by dstokesf5** [comment]
Created internal product backlog item AUTOTOOL-1076 to update the documentation.

**Comment by emmanuelgirard** [comment]
We also need to have a full version of the do json schema along all the files in the schema folder.

**Comment by dstokesf5** [comment]
Documentation has been updated. Closing this issue.
