### ISSUE TITLE
Server Error 500 when applying DO JSON in 1.9.0

### ISSUE THREAD

**Issue by ToniCipriani** [F5Networks/f5-declarative-onboarding#99]
Attempting to build a cluster of Azure LB with 2 F5 BIG-IP Nodes in avail set via Terraform. When using DO, DO returns with a 500 server error

"errors":["Cannot read property 'includes' of undefined","Cannot read property 'includes' of undefined"]

[do_config.json.txt](https://github.com/F5Networks/f5-declarative-onboarding/files/4066252/do_config.json.txt)

**Comment by dstokesf5** [comment]
Sorry, it looks like the link I sent you skipped our template. Can you please resubmit this issue through our template via this link: https://github.com/F5Networks/f5-declarative-onboarding/issues/new?assignees=&labels=bug%2C+untriaged&template=bug_report.md&title=

**Comment by ToniCipriani** [comment]
Resubmitted as https://github.com/F5Networks/f5-declarative-onboarding/issues/100

**Comment by dstokesf5** [comment]
I really appreciate you resubmitting the issue. That helps us better handle your bug report. Closing this one.
